version: '3'

services:
  db:
    image: mdillon/postgis:9.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  cache:
    image: memcached:1.5-alpine
    ports:
      - "51212:11211"

  elasticsearch:
    image: elasticsearch:2.4-alpine
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "59200:9200"

  redis:
    image: redis:4-alpine
    ports:
      - "56379:6379"

volumes:
  pgdata:
  esdata: