# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_to_collection_fk(apps, schema_editor):
    Collection = apps.get_model("website", "Collection")
    db_alias = schema_editor.connection.alias
    for coll in Collection.objects.using(db_alias).all():
        coll.items.update(collection=coll)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(related_name='collection_m2m', to='website.CollectionItem'),
        ),
        migrations.RunPython(
            forwards_to_collection_fk,
        ),
    ]
