# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160822_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='items',
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Collection', related_name='items'),
        ),
    ]
