# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_collectionitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['collection_id', 'order']},
        ),
    ]
