# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import markymark.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160822_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='description',
            field=markymark.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='description_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
