# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 18:53
from __future__ import unicode_literals

from django.db import migrations
import markymark.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160823_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='description',
            field=markymark.fields.MarkdownField(blank=True, help_text='Teaser/description. Keep it short.'),
        ),
    ]
