"""
list of fields that are included in the output data
"""
FIELDS = [
    "Dataset",
    "Type",
    "Power Plant Name",
    "Project Name",

    "Infrastructure Type",
    "Country",
    "Region",
    "Latitude",
    "Longitude",

    "Plant Status",
    "Plant Day Online",
    "Plant Month Online",
    "Plant Year Online",
    "Decommissioning Day",
    "Decommissioning Month",
    "Decommissioning Year",

    "Plant Capacity",
    "Plant Capacity Unit",
    "Plant Output",
    "Plant Output Unit",
    "Plant Output Year",
    "Estimated Plant Output",
    "Estimated Plant Output Unit",
    "Plant CO2 Emissions",
    "Plant CO2 Emissions Unit",
    "Plant Fuel 1",
    "Plant Fuel 1 Category",
    "Plant Fuel 2",
    "Plant Fuel 2 Category",
    "Plant Fuel 3",
    "Plant Fuel 3 Category",
    "Plant Fuel 4",
    "Plant Fuel 4 Category",
    "Plant Fuel 5",
    "Plant Fuel 5 Category",
    "Plant Fuel 6",
    "Plant Fuel 6 Category",
    "Plant Fuel 7",
    "Plant Fuel 7 Category",

    "Project Status",
    "Project Capacity",
    "Project Capacity Unit",
    "Project Output",
    "Project Output Unit",
    "Estimated Project Output",
    "Estimated Project Output Unit",
    "Project CO2 Emissions",
    "Project CO2 Emissions Unit",
    "Project Fuel 1",
    "Project Fuel 1 Category",
    "Project Fuel 2",
    "Project Fuel 2 Category",
    "Project Fuel 3",
    "Project Fuel 3 Category",
    "Project Fuel 4",
    "Project Fuel 4 Category",

    "Grid Connected",
    "SOx Reduction System",
    "NOx Reduction System",

    "Total Cost",
    "Total Cost Currency",

    "Start Day",
    "Start Month",
    "Start Year",

    "Construction Start Day",
    "Construction Start Month",
    "Construction Start Year",

    "Completion Day",
    "Completion Month",
    "Completion Year",
    "New Construction",
    "Initiative",

    "Contractor 1",
    "Contractor 2",
    "Contractor 3",
    "Contractor 4",
    "Contractor 5",
    "Contractor 6",
    "Contractor 7",
    "Contractor 8",
    "Contractor 9",
    "Contractor 10",
    "Consultant",
    "Implementing Agency",

    "Manufacturer 1",
    "Manufacturer 2",
    "Manufacturer 3",
    "Manufacturer 4",
    "Manufacturer 5",

    "Owner 1",
    "Owner 1 Stake",
    "Owner 2",
    "Owner 2 Stake",
    "Owner 3",
    "Owner 3 Stake",
    "Owner 4",
    "Owner 4 Stake",
    "Owner 5",
    "Owner 5 Stake",
    "Owner 6",
    "Owner 6 Stake",
    "Owner 7",
    "Owner 7 Stake",
    "Owner 8",
    "Owner 8 Stake",
    "Owner 9",
    "Owner 9 Stake",
    "Owner 10",
    "Owner 10 Stake",

    "Operator 1",
    "Operator 2",
    "Operator 3",
    "Operator 4",

    "Funder 1",
    "Funding Amount 1",
    "Funding Currency 1",
    "Funder 2",
    "Funding Amount 2",
    "Funding Currency 2",

    "Sources",
    "Notes",
]

