# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 18:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import markymark.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_geocollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Structure')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', markymark.fields.MarkdownField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', markymark.fields.MarkdownField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinancingRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilitaryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultilateralMemberRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultilateralRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultilateralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NGOMemberRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NGORelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NGOType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'NGO type',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', markymark.fields.MarkdownField(blank=True)),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('dissolution_date', models.DateField(blank=True, null=True)),
                ('staff_size', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Staff/Personnel count')),
                ('mission', markymark.fields.MarkdownField(blank=True, verbose_name='Mandate/Mission Statement')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationShareholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Share')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('given_name', models.CharField(help_text="A person's given or 'first' name(s).", max_length=100, verbose_name='First name')),
                ('additional_name', models.CharField(blank=True, help_text="An additional name for a person,                                                                               such as a 'middle' name.", max_length=100, verbose_name='Middle name')),
                ('family_name', models.CharField(blank=True, help_text="A person's family or 'last' name(s).", max_length=140, verbose_name='Last name')),
                ('citizenships', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(4, 'Afghanistan'), (248, 'Åland Islands'), (8, 'Albania'), (12, 'Algeria'), (16, 'American Samoa'), (20, 'Andorra'), (24, 'Angola'), (660, 'Anguilla'), (10, 'Antarctica'), (28, 'Antigua and Barbuda'), (32, 'Argentina'), (51, 'Armenia'), (533, 'Aruba'), (36, 'Australia'), (40, 'Austria'), (31, 'Azerbaijan'), (44, 'Bahamas'), (48, 'Bahrain'), (50, 'Bangladesh'), (52, 'Barbados'), (112, 'Belarus'), (56, 'Belgium'), (84, 'Belize'), (204, 'Benin'), (60, 'Bermuda'), (64, 'Bhutan'), (68, 'Bolivia, Plurinational State of'), (535, 'Bonaire, Sint Eustatius and Saba'), (70, 'Bosnia and Herzegovina'), (72, 'Botswana'), (74, 'Bouvet Island'), (76, 'Brazil'), (86, 'British Indian Ocean Territory'), (96, 'Brunei Darussalam'), (100, 'Bulgaria'), (854, 'Burkina Faso'), (108, 'Burundi'), (116, 'Cambodia'), (120, 'Cameroon'), (124, 'Canada'), (132, 'Cabo Verde'), (136, 'Cayman Islands'), (140, 'Central African Republic'), (148, 'Chad'), (152, 'Chile'), (156, 'China'), (162, 'Christmas Island'), (166, 'Cocos (Keeling) Islands'), (170, 'Colombia'), (174, 'Comoros'), (178, 'Congo'), (180, 'Congo, Democratic Republic of the'), (184, 'Cook Islands'), (188, 'Costa Rica'), (384, "Côte d'Ivoire"), (191, 'Croatia'), (192, 'Cuba'), (531, 'Curaçao'), (196, 'Cyprus'), (203, 'Czech Republic'), (208, 'Denmark'), (262, 'Djibouti'), (212, 'Dominica'), (214, 'Dominican Republic'), (218, 'Ecuador'), (818, 'Egypt'), (222, 'El Salvador'), (226, 'Equatorial Guinea'), (232, 'Eritrea'), (233, 'Estonia'), (231, 'Ethiopia'), (238, 'Falkland Islands (Malvinas)'), (234, 'Faroe Islands'), (242, 'Fiji'), (246, 'Finland'), (250, 'France'), (254, 'French Guiana'), (258, 'French Polynesia'), (260, 'French Southern Territories'), (266, 'Gabon'), (270, 'Gambia'), (268, 'Georgia'), (276, 'Germany'), (288, 'Ghana'), (292, 'Gibraltar'), (300, 'Greece'), (304, 'Greenland'), (308, 'Grenada'), (312, 'Guadeloupe'), (316, 'Guam'), (320, 'Guatemala'), (831, 'Guernsey'), (324, 'Guinea'), (624, 'Guinea-Bissau'), (328, 'Guyana'), (332, 'Haiti'), (334, 'Heard Island and McDonald Islands'), (336, 'Holy See'), (340, 'Honduras'), (344, 'Hong Kong'), (348, 'Hungary'), (352, 'Iceland'), (356, 'India'), (360, 'Indonesia'), (364, 'Iran, Islamic Republic of'), (368, 'Iraq'), (372, 'Ireland'), (833, 'Isle of Man'), (376, 'Israel'), (380, 'Italy'), (388, 'Jamaica'), (392, 'Japan'), (832, 'Jersey'), (400, 'Jordan'), (398, 'Kazakhstan'), (404, 'Kenya'), (296, 'Kiribati'), (408, "Korea, Democratic People's Republic of"), (410, 'Korea, Republic of'), (414, 'Kuwait'), (417, 'Kyrgyzstan'), (418, "Lao People's Democratic Republic"), (428, 'Latvia'), (422, 'Lebanon'), (426, 'Lesotho'), (430, 'Liberia'), (434, 'Libya'), (438, 'Liechtenstein'), (440, 'Lithuania'), (442, 'Luxembourg'), (446, 'Macao'), (807, 'Macedonia, the former Yugoslav Republic of'), (450, 'Madagascar'), (454, 'Malawi'), (458, 'Malaysia'), (462, 'Maldives'), (466, 'Mali'), (470, 'Malta'), (584, 'Marshall Islands'), (474, 'Martinique'), (478, 'Mauritania'), (480, 'Mauritius'), (175, 'Mayotte'), (484, 'Mexico'), (583, 'Micronesia, Federated States of'), (498, 'Moldova, Republic of'), (492, 'Monaco'), (496, 'Mongolia'), (499, 'Montenegro'), (500, 'Montserrat'), (504, 'Morocco'), (508, 'Mozambique'), (104, 'Myanmar'), (516, 'Namibia'), (520, 'Nauru'), (524, 'Nepal'), (528, 'Netherlands'), (540, 'New Caledonia'), (554, 'New Zealand'), (558, 'Nicaragua'), (562, 'Niger'), (566, 'Nigeria'), (570, 'Niue'), (574, 'Norfolk Island'), (580, 'Northern Mariana Islands'), (578, 'Norway'), (512, 'Oman'), (586, 'Pakistan'), (585, 'Palau'), (275, 'Palestine, State of'), (591, 'Panama'), (598, 'Papua New Guinea'), (600, 'Paraguay'), (604, 'Peru'), (608, 'Philippines'), (612, 'Pitcairn'), (616, 'Poland'), (620, 'Portugal'), (630, 'Puerto Rico'), (634, 'Qatar'), (638, 'Réunion'), (642, 'Romania'), (643, 'Russian Federation'), (646, 'Rwanda'), (652, 'Saint Barthélemy'), (654, 'Saint Helena, Ascension and Tristan da Cunha'), (659, 'Saint Kitts and Nevis'), (662, 'Saint Lucia'), (663, 'Saint Martin (French part)'), (666, 'Saint Pierre and Miquelon'), (670, 'Saint Vincent and the Grenadines'), (882, 'Samoa'), (674, 'San Marino'), (678, 'Sao Tome and Principe'), (682, 'Saudi Arabia'), (686, 'Senegal'), (688, 'Serbia'), (690, 'Seychelles'), (694, 'Sierra Leone'), (702, 'Singapore'), (534, 'Sint Maarten (Dutch part)'), (703, 'Slovakia'), (705, 'Slovenia'), (90, 'Solomon Islands'), (706, 'Somalia'), (710, 'South Africa'), (239, 'South Georgia and the South Sandwich Islands'), (728, 'South Sudan'), (724, 'Spain'), (144, 'Sri Lanka'), (729, 'Sudan'), (740, 'Suriname'), (744, 'Svalbard and Jan Mayen'), (748, 'Swaziland'), (752, 'Sweden'), (756, 'Switzerland'), (760, 'Syrian Arab Republic'), (158, 'Taiwan, Province of China'), (762, 'Tajikistan'), (834, 'Tanzania, United Republic of'), (764, 'Thailand'), (626, 'Timor-Leste'), (768, 'Togo'), (772, 'Tokelau'), (776, 'Tonga'), (780, 'Trinidad and Tobago'), (788, 'Tunisia'), (792, 'Turkey'), (795, 'Turkmenistan'), (796, 'Turks and Caicos Islands'), (798, 'Tuvalu'), (800, 'Uganda'), (804, 'Ukraine'), (784, 'United Arab Emirates'), (826, 'United Kingdom'), (840, 'United States'), (581, 'United States Minor Outlying Islands'), (858, 'Uruguay'), (860, 'Uzbekistan'), (548, 'Vanuatu'), (862, 'Venezuela, Bolivarian Republic of'), (704, 'Viet Nam'), (92, 'Virgin Islands, British'), (850, 'Virgin Islands, U.S.'), (876, 'Wallis and Futuna'), (732, 'Western Sahara'), (887, 'Yemen'), (894, 'Zambia'), (716, 'Zimbabwe')]), blank=True, default=list, null=True, size=None)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('notes', markymark.fields.MarkdownField(blank=True)),
                ('events', models.ManyToManyField(blank=True, to='facts.Event')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='PersonShareholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Share')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Person', verbose_name='from')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoliticalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoliticalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facts.PoliticalType')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'position (job)',
                'verbose_name_plural': 'positions (jobs)',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facts.Organization')),
                ('sector', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary')], null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
            bases=('facts.organization',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinancingOrganization',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facts.Organization')),
                ('approved_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
                ('moodys_credit_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aaa'), (2, 'Aa1'), (3, 'Aa2'), (4, 'Aa3'), (5, 'A1'), (6, 'A2'), (7, 'A3'), (8, 'Baa1'), (9, 'Baa2'), (10, 'Baa3'), (11, 'Ba1'), (12, 'Ba2'), (13, 'Ba3'), (14, 'B1'), (15, 'B2'), (16, 'B3'), (17, 'Caa1'), (18, 'Caa2'), (19, 'Caa3'), (20, 'Ca'), (21, 'C')], null=True)),
                ('fitch_credit_rating', models.PositiveSmallIntegerField(blank=True, choices=[(101, 'AAA'), (102, 'AA+'), (103, 'AA'), (104, 'AA−'), (105, 'A+'), (106, 'A'), (107, 'A−'), (108, 'BBB+'), (109, 'BBB'), (110, 'BBB−'), (111, 'BB+'), (112, 'BB'), (113, 'BB−'), (114, 'B+'), (115, 'B'), (116, 'B−'), (117, 'CCC+'), (118, 'CCC'), (119, 'CCC−'), (120, 'CC'), (121, 'C'), (122, 'DDD'), (123, 'DD'), (124, 'D')], null=True)),
                ('sp_credit_rating', models.PositiveSmallIntegerField(blank=True, choices=[(201, 'AAA'), (202, 'AA+'), (203, 'AA'), (204, 'AA−'), (205, 'A+'), (206, 'A'), (207, 'A−'), (208, 'BBB+'), (209, 'BBB'), (210, 'BBB−'), (211, 'BB+'), (212, 'BB'), (213, 'BB−'), (214, 'B+'), (215, 'B'), (216, 'B−'), (217, 'CCC+'), (218, 'CCC'), (219, 'CCC−'), (220, 'CC'), (221, 'C'), (222, 'RD'), (223, 'SD'), (224, 'D')], null=True)),
                ('scope_of_operations', models.CharField(blank=True, max_length=100)),
                ('procurement', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('facts.organization',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facts.Organization')),
                ('country', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Afghanistan'), (248, 'Åland Islands'), (8, 'Albania'), (12, 'Algeria'), (16, 'American Samoa'), (20, 'Andorra'), (24, 'Angola'), (660, 'Anguilla'), (10, 'Antarctica'), (28, 'Antigua and Barbuda'), (32, 'Argentina'), (51, 'Armenia'), (533, 'Aruba'), (36, 'Australia'), (40, 'Austria'), (31, 'Azerbaijan'), (44, 'Bahamas'), (48, 'Bahrain'), (50, 'Bangladesh'), (52, 'Barbados'), (112, 'Belarus'), (56, 'Belgium'), (84, 'Belize'), (204, 'Benin'), (60, 'Bermuda'), (64, 'Bhutan'), (68, 'Bolivia, Plurinational State of'), (535, 'Bonaire, Sint Eustatius and Saba'), (70, 'Bosnia and Herzegovina'), (72, 'Botswana'), (74, 'Bouvet Island'), (76, 'Brazil'), (86, 'British Indian Ocean Territory'), (96, 'Brunei Darussalam'), (100, 'Bulgaria'), (854, 'Burkina Faso'), (108, 'Burundi'), (116, 'Cambodia'), (120, 'Cameroon'), (124, 'Canada'), (132, 'Cabo Verde'), (136, 'Cayman Islands'), (140, 'Central African Republic'), (148, 'Chad'), (152, 'Chile'), (156, 'China'), (162, 'Christmas Island'), (166, 'Cocos (Keeling) Islands'), (170, 'Colombia'), (174, 'Comoros'), (178, 'Congo'), (180, 'Congo, Democratic Republic of the'), (184, 'Cook Islands'), (188, 'Costa Rica'), (384, "Côte d'Ivoire"), (191, 'Croatia'), (192, 'Cuba'), (531, 'Curaçao'), (196, 'Cyprus'), (203, 'Czech Republic'), (208, 'Denmark'), (262, 'Djibouti'), (212, 'Dominica'), (214, 'Dominican Republic'), (218, 'Ecuador'), (818, 'Egypt'), (222, 'El Salvador'), (226, 'Equatorial Guinea'), (232, 'Eritrea'), (233, 'Estonia'), (231, 'Ethiopia'), (238, 'Falkland Islands (Malvinas)'), (234, 'Faroe Islands'), (242, 'Fiji'), (246, 'Finland'), (250, 'France'), (254, 'French Guiana'), (258, 'French Polynesia'), (260, 'French Southern Territories'), (266, 'Gabon'), (270, 'Gambia'), (268, 'Georgia'), (276, 'Germany'), (288, 'Ghana'), (292, 'Gibraltar'), (300, 'Greece'), (304, 'Greenland'), (308, 'Grenada'), (312, 'Guadeloupe'), (316, 'Guam'), (320, 'Guatemala'), (831, 'Guernsey'), (324, 'Guinea'), (624, 'Guinea-Bissau'), (328, 'Guyana'), (332, 'Haiti'), (334, 'Heard Island and McDonald Islands'), (336, 'Holy See'), (340, 'Honduras'), (344, 'Hong Kong'), (348, 'Hungary'), (352, 'Iceland'), (356, 'India'), (360, 'Indonesia'), (364, 'Iran, Islamic Republic of'), (368, 'Iraq'), (372, 'Ireland'), (833, 'Isle of Man'), (376, 'Israel'), (380, 'Italy'), (388, 'Jamaica'), (392, 'Japan'), (832, 'Jersey'), (400, 'Jordan'), (398, 'Kazakhstan'), (404, 'Kenya'), (296, 'Kiribati'), (408, "Korea, Democratic People's Republic of"), (410, 'Korea, Republic of'), (414, 'Kuwait'), (417, 'Kyrgyzstan'), (418, "Lao People's Democratic Republic"), (428, 'Latvia'), (422, 'Lebanon'), (426, 'Lesotho'), (430, 'Liberia'), (434, 'Libya'), (438, 'Liechtenstein'), (440, 'Lithuania'), (442, 'Luxembourg'), (446, 'Macao'), (807, 'Macedonia, the former Yugoslav Republic of'), (450, 'Madagascar'), (454, 'Malawi'), (458, 'Malaysia'), (462, 'Maldives'), (466, 'Mali'), (470, 'Malta'), (584, 'Marshall Islands'), (474, 'Martinique'), (478, 'Mauritania'), (480, 'Mauritius'), (175, 'Mayotte'), (484, 'Mexico'), (583, 'Micronesia, Federated States of'), (498, 'Moldova, Republic of'), (492, 'Monaco'), (496, 'Mongolia'), (499, 'Montenegro'), (500, 'Montserrat'), (504, 'Morocco'), (508, 'Mozambique'), (104, 'Myanmar'), (516, 'Namibia'), (520, 'Nauru'), (524, 'Nepal'), (528, 'Netherlands'), (540, 'New Caledonia'), (554, 'New Zealand'), (558, 'Nicaragua'), (562, 'Niger'), (566, 'Nigeria'), (570, 'Niue'), (574, 'Norfolk Island'), (580, 'Northern Mariana Islands'), (578, 'Norway'), (512, 'Oman'), (586, 'Pakistan'), (585, 'Palau'), (275, 'Palestine, State of'), (591, 'Panama'), (598, 'Papua New Guinea'), (600, 'Paraguay'), (604, 'Peru'), (608, 'Philippines'), (612, 'Pitcairn'), (616, 'Poland'), (620, 'Portugal'), (630, 'Puerto Rico'), (634, 'Qatar'), (638, 'Réunion'), (642, 'Romania'), (643, 'Russian Federation'), (646, 'Rwanda'), (652, 'Saint Barthélemy'), (654, 'Saint Helena, Ascension and Tristan da Cunha'), (659, 'Saint Kitts and Nevis'), (662, 'Saint Lucia'), (663, 'Saint Martin (French part)'), (666, 'Saint Pierre and Miquelon'), (670, 'Saint Vincent and the Grenadines'), (882, 'Samoa'), (674, 'San Marino'), (678, 'Sao Tome and Principe'), (682, 'Saudi Arabia'), (686, 'Senegal'), (688, 'Serbia'), (690, 'Seychelles'), (694, 'Sierra Leone'), (702, 'Singapore'), (534, 'Sint Maarten (Dutch part)'), (703, 'Slovakia'), (705, 'Slovenia'), (90, 'Solomon Islands'), (706, 'Somalia'), (710, 'South Africa'), (239, 'South Georgia and the South Sandwich Islands'), (728, 'South Sudan'), (724, 'Spain'), (144, 'Sri Lanka'), (729, 'Sudan'), (740, 'Suriname'), (744, 'Svalbard and Jan Mayen'), (748, 'Swaziland'), (752, 'Sweden'), (756, 'Switzerland'), (760, 'Syrian Arab Republic'), (158, 'Taiwan, Province of China'), (762, 'Tajikistan'), (834, 'Tanzania, United Republic of'), (764, 'Thailand'), (626, 'Timor-Leste'), (768, 'Togo'), (772, 'Tokelau'), (776, 'Tonga'), (780, 'Trinidad and Tobago'), (788, 'Tunisia'), (792, 'Turkey'), (795, 'Turkmenistan'), (796, 'Turks and Caicos Islands'), (798, 'Tuvalu'), (800, 'Uganda'), (804, 'Ukraine'), (784, 'United Arab Emirates'), (826, 'United Kingdom'), (840, 'United States'), (581, 'United States Minor Outlying Islands'), (858, 'Uruguay'), (860, 'Uzbekistan'), (548, 'Vanuatu'), (862, 'Venezuela, Bolivarian Republic of'), (704, 'Viet Nam'), (92, 'Virgin Islands, British'), (850, 'Virgin Islands, U.S.'), (876, 'Wallis and Futuna'), (732, 'Western Sahara'), (887, 'Yemen'), (894, 'Zambia'), (716, 'Zimbabwe')], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('facts.organization',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Military',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facts.Organization')),
                ('country', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Afghanistan'), (248, 'Åland Islands'), (8, 'Albania'), (12, 'Algeria'), (16, 'American Samoa'), (20, 'Andorra'), (24, 'Angola'), (660, 'Anguilla'), (10, 'Antarctica'), (28, 'Antigua and Barbuda'), (32, 'Argentina'), (51, 'Armenia'), (533, 'Aruba'), (36, 'Australia'), (40, 'Austria'), (31, 'Azerbaijan'), (44, 'Bahamas'), (48, 'Bahrain'), (50, 'Bangladesh'), (52, 'Barbados'), (112, 'Belarus'), (56, 'Belgium'), (84, 'Belize'), (204, 'Benin'), (60, 'Bermuda'), (64, 'Bhutan'), (68, 'Bolivia, Plurinational State of'), (535, 'Bonaire, Sint Eustatius and Saba'), (70, 'Bosnia and Herzegovina'), (72, 'Botswana'), (74, 'Bouvet Island'), (76, 'Brazil'), (86, 'British Indian Ocean Territory'), (96, 'Brunei Darussalam'), (100, 'Bulgaria'), (854, 'Burkina Faso'), (108, 'Burundi'), (116, 'Cambodia'), (120, 'Cameroon'), (124, 'Canada'), (132, 'Cabo Verde'), (136, 'Cayman Islands'), (140, 'Central African Republic'), (148, 'Chad'), (152, 'Chile'), (156, 'China'), (162, 'Christmas Island'), (166, 'Cocos (Keeling) Islands'), (170, 'Colombia'), (174, 'Comoros'), (178, 'Congo'), (180, 'Congo, Democratic Republic of the'), (184, 'Cook Islands'), (188, 'Costa Rica'), (384, "Côte d'Ivoire"), (191, 'Croatia'), (192, 'Cuba'), (531, 'Curaçao'), (196, 'Cyprus'), (203, 'Czech Republic'), (208, 'Denmark'), (262, 'Djibouti'), (212, 'Dominica'), (214, 'Dominican Republic'), (218, 'Ecuador'), (818, 'Egypt'), (222, 'El Salvador'), (226, 'Equatorial Guinea'), (232, 'Eritrea'), (233, 'Estonia'), (231, 'Ethiopia'), (238, 'Falkland Islands (Malvinas)'), (234, 'Faroe Islands'), (242, 'Fiji'), (246, 'Finland'), (250, 'France'), (254, 'French Guiana'), (258, 'French Polynesia'), (260, 'French Southern Territories'), (266, 'Gabon'), (270, 'Gambia'), (268, 'Georgia'), (276, 'Germany'), (288, 'Ghana'), (292, 'Gibraltar'), (300, 'Greece'), (304, 'Greenland'), (308, 'Grenada'), (312, 'Guadeloupe'), (316, 'Guam'), (320, 'Guatemala'), (831, 'Guernsey'), (324, 'Guinea'), (624, 'Guinea-Bissau'), (328, 'Guyana'), (332, 'Haiti'), (334, 'Heard Island and McDonald Islands'), (336, 'Holy See'), (340, 'Honduras'), (344, 'Hong Kong'), (348, 'Hungary'), (352, 'Iceland'), (356, 'India'), (360, 'Indonesia'), (364, 'Iran, Islamic Republic of'), (368, 'Iraq'), (372, 'Ireland'), (833, 'Isle of Man'), (376, 'Israel'), (380, 'Italy'), (388, 'Jamaica'), (392, 'Japan'), (832, 'Jersey'), (400, 'Jordan'), (398, 'Kazakhstan'), (404, 'Kenya'), (296, 'Kiribati'), (408, "Korea, Democratic People's Republic of"), (410, 'Korea, Republic of'), (414, 'Kuwait'), (417, 'Kyrgyzstan'), (418, "Lao People's Democratic Republic"), (428, 'Latvia'), (422, 'Lebanon'), (426, 'Lesotho'), (430, 'Liberia'), (434, 'Libya'), (438, 'Liechtenstein'), (440, 'Lithuania'), (442, 'Luxembourg'), (446, 'Macao'), (807, 'Macedonia, the former Yugoslav Republic of'), (450, 'Madagascar'), (454, 'Malawi'), (458, 'Malaysia'), (462, 'Maldives'), (466, 'Mali'), (470, 'Malta'), (584, 'Marshall Islands'), (474, 'Martinique'), (478, 'Mauritania'), (480, 'Mauritius'), (175, 'Mayotte'), (484, 'Mexico'), (583, 'Micronesia, Federated States of'), (498, 'Moldova, Republic of'), (492, 'Monaco'), (496, 'Mongolia'), (499, 'Montenegro'), (500, 'Montserrat'), (504, 'Morocco'), (508, 'Mozambique'), (104, 'Myanmar'), (516, 'Namibia'), (520, 'Nauru'), (524, 'Nepal'), (528, 'Netherlands'), (540, 'New Caledonia'), (554, 'New Zealand'), (558, 'Nicaragua'), (562, 'Niger'), (566, 'Nigeria'), (570, 'Niue'), (574, 'Norfolk Island'), (580, 'Northern Mariana Islands'), (578, 'Norway'), (512, 'Oman'), (586, 'Pakistan'), (585, 'Palau'), (275, 'Palestine, State of'), (591, 'Panama'), (598, 'Papua New Guinea'), (600, 'Paraguay'), (604, 'Peru'), (608, 'Philippines'), (612, 'Pitcairn'), (616, 'Poland'), (620, 'Portugal'), (630, 'Puerto Rico'), (634, 'Qatar'), (638, 'Réunion'), (642, 'Romania'), (643, 'Russian Federation'), (646, 'Rwanda'), (652, 'Saint Barthélemy'), (654, 'Saint Helena, Ascension and Tristan da Cunha'), (659, 'Saint Kitts and Nevis'), (662, 'Saint Lucia'), (663, 'Saint Martin (French part)'), (666, 'Saint Pierre and Miquelon'), (670, 'Saint Vincent and the Grenadines'), (882, 'Samoa'), (674, 'San Marino'), (678, 'Sao Tome and Principe'), (682, 'Saudi Arabia'), (686, 'Senegal'), (688, 'Serbia'), (690, 'Seychelles'), (694, 'Sierra Leone'), (702, 'Singapore'), (534, 'Sint Maarten (Dutch part)'), (703, 'Slovakia'), (705, 'Slovenia'), (90, 'Solomon Islands'), (706, 'Somalia'), (710, 'South Africa'), (239, 'South Georgia and the South Sandwich Islands'), (728, 'South Sudan'), (724, 'Spain'), (144, 'Sri Lanka'), (729, 'Sudan'), (740, 'Suriname'), (744, 'Svalbard and Jan Mayen'), (748, 'Swaziland'), (752, 'Sweden'), (756, 'Switzerland'), (760, 'Syrian Arab Republic'), (158, 'Taiwan, Province of China'), (762, 'Tajikistan'), (834, 'Tanzania, United Republic of'), (764, 'Thailand'), (626, 'Timor-Leste'), (768, 'Togo'), (772, 'Tokelau'), (776, 'Tonga'), (780, 'Trinidad and Tobago'), (788, 'Tunisia'), (792, 'Turkey'), (795, 'Turkmenistan'), (796, 'Turks and Caicos Islands'), (798, 'Tuvalu'), (800, 'Uganda'), (804, 'Ukraine'), (784, 'United Arab Emirates'), (826, 'United Kingdom'), (840, 'United States'), (581, 'United States Minor Outlying Islands'), (858, 'Uruguay'), (860, 'Uzbekistan'), (548, 'Vanuatu'), (862, 'Venezuela, Bolivarian Republic of'), (704, 'Viet Nam'), (92, 'Virgin Islands, British'), (850, 'Virgin Islands, U.S.'), (876, 'Wallis and Futuna'), (732, 'Western Sahara'), (887, 'Yemen'), (894, 'Zambia'), (716, 'Zimbabwe')], null=True)),
                ('ruling_party', models.BooleanField(default=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
            ],
            options={
                'verbose_name_plural': 'militaries',
            },
            bases=('facts.organization',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Multilateral',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facts.Organization')),
            ],
            options={
                'abstract': False,
            },
            bases=('facts.organization',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facts.Organization')),
                ('endowment', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
            ],
            options={
                'verbose_name': 'NGO',
            },
            bases=('facts.organization',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Political',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facts.Organization')),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(4, 'Afghanistan'), (248, 'Åland Islands'), (8, 'Albania'), (12, 'Algeria'), (16, 'American Samoa'), (20, 'Andorra'), (24, 'Angola'), (660, 'Anguilla'), (10, 'Antarctica'), (28, 'Antigua and Barbuda'), (32, 'Argentina'), (51, 'Armenia'), (533, 'Aruba'), (36, 'Australia'), (40, 'Austria'), (31, 'Azerbaijan'), (44, 'Bahamas'), (48, 'Bahrain'), (50, 'Bangladesh'), (52, 'Barbados'), (112, 'Belarus'), (56, 'Belgium'), (84, 'Belize'), (204, 'Benin'), (60, 'Bermuda'), (64, 'Bhutan'), (68, 'Bolivia, Plurinational State of'), (535, 'Bonaire, Sint Eustatius and Saba'), (70, 'Bosnia and Herzegovina'), (72, 'Botswana'), (74, 'Bouvet Island'), (76, 'Brazil'), (86, 'British Indian Ocean Territory'), (96, 'Brunei Darussalam'), (100, 'Bulgaria'), (854, 'Burkina Faso'), (108, 'Burundi'), (116, 'Cambodia'), (120, 'Cameroon'), (124, 'Canada'), (132, 'Cabo Verde'), (136, 'Cayman Islands'), (140, 'Central African Republic'), (148, 'Chad'), (152, 'Chile'), (156, 'China'), (162, 'Christmas Island'), (166, 'Cocos (Keeling) Islands'), (170, 'Colombia'), (174, 'Comoros'), (178, 'Congo'), (180, 'Congo, Democratic Republic of the'), (184, 'Cook Islands'), (188, 'Costa Rica'), (384, "Côte d'Ivoire"), (191, 'Croatia'), (192, 'Cuba'), (531, 'Curaçao'), (196, 'Cyprus'), (203, 'Czech Republic'), (208, 'Denmark'), (262, 'Djibouti'), (212, 'Dominica'), (214, 'Dominican Republic'), (218, 'Ecuador'), (818, 'Egypt'), (222, 'El Salvador'), (226, 'Equatorial Guinea'), (232, 'Eritrea'), (233, 'Estonia'), (231, 'Ethiopia'), (238, 'Falkland Islands (Malvinas)'), (234, 'Faroe Islands'), (242, 'Fiji'), (246, 'Finland'), (250, 'France'), (254, 'French Guiana'), (258, 'French Polynesia'), (260, 'French Southern Territories'), (266, 'Gabon'), (270, 'Gambia'), (268, 'Georgia'), (276, 'Germany'), (288, 'Ghana'), (292, 'Gibraltar'), (300, 'Greece'), (304, 'Greenland'), (308, 'Grenada'), (312, 'Guadeloupe'), (316, 'Guam'), (320, 'Guatemala'), (831, 'Guernsey'), (324, 'Guinea'), (624, 'Guinea-Bissau'), (328, 'Guyana'), (332, 'Haiti'), (334, 'Heard Island and McDonald Islands'), (336, 'Holy See'), (340, 'Honduras'), (344, 'Hong Kong'), (348, 'Hungary'), (352, 'Iceland'), (356, 'India'), (360, 'Indonesia'), (364, 'Iran, Islamic Republic of'), (368, 'Iraq'), (372, 'Ireland'), (833, 'Isle of Man'), (376, 'Israel'), (380, 'Italy'), (388, 'Jamaica'), (392, 'Japan'), (832, 'Jersey'), (400, 'Jordan'), (398, 'Kazakhstan'), (404, 'Kenya'), (296, 'Kiribati'), (408, "Korea, Democratic People's Republic of"), (410, 'Korea, Republic of'), (414, 'Kuwait'), (417, 'Kyrgyzstan'), (418, "Lao People's Democratic Republic"), (428, 'Latvia'), (422, 'Lebanon'), (426, 'Lesotho'), (430, 'Liberia'), (434, 'Libya'), (438, 'Liechtenstein'), (440, 'Lithuania'), (442, 'Luxembourg'), (446, 'Macao'), (807, 'Macedonia, the former Yugoslav Republic of'), (450, 'Madagascar'), (454, 'Malawi'), (458, 'Malaysia'), (462, 'Maldives'), (466, 'Mali'), (470, 'Malta'), (584, 'Marshall Islands'), (474, 'Martinique'), (478, 'Mauritania'), (480, 'Mauritius'), (175, 'Mayotte'), (484, 'Mexico'), (583, 'Micronesia, Federated States of'), (498, 'Moldova, Republic of'), (492, 'Monaco'), (496, 'Mongolia'), (499, 'Montenegro'), (500, 'Montserrat'), (504, 'Morocco'), (508, 'Mozambique'), (104, 'Myanmar'), (516, 'Namibia'), (520, 'Nauru'), (524, 'Nepal'), (528, 'Netherlands'), (540, 'New Caledonia'), (554, 'New Zealand'), (558, 'Nicaragua'), (562, 'Niger'), (566, 'Nigeria'), (570, 'Niue'), (574, 'Norfolk Island'), (580, 'Northern Mariana Islands'), (578, 'Norway'), (512, 'Oman'), (586, 'Pakistan'), (585, 'Palau'), (275, 'Palestine, State of'), (591, 'Panama'), (598, 'Papua New Guinea'), (600, 'Paraguay'), (604, 'Peru'), (608, 'Philippines'), (612, 'Pitcairn'), (616, 'Poland'), (620, 'Portugal'), (630, 'Puerto Rico'), (634, 'Qatar'), (638, 'Réunion'), (642, 'Romania'), (643, 'Russian Federation'), (646, 'Rwanda'), (652, 'Saint Barthélemy'), (654, 'Saint Helena, Ascension and Tristan da Cunha'), (659, 'Saint Kitts and Nevis'), (662, 'Saint Lucia'), (663, 'Saint Martin (French part)'), (666, 'Saint Pierre and Miquelon'), (670, 'Saint Vincent and the Grenadines'), (882, 'Samoa'), (674, 'San Marino'), (678, 'Sao Tome and Principe'), (682, 'Saudi Arabia'), (686, 'Senegal'), (688, 'Serbia'), (690, 'Seychelles'), (694, 'Sierra Leone'), (702, 'Singapore'), (534, 'Sint Maarten (Dutch part)'), (703, 'Slovakia'), (705, 'Slovenia'), (90, 'Solomon Islands'), (706, 'Somalia'), (710, 'South Africa'), (239, 'South Georgia and the South Sandwich Islands'), (728, 'South Sudan'), (724, 'Spain'), (144, 'Sri Lanka'), (729, 'Sudan'), (740, 'Suriname'), (744, 'Svalbard and Jan Mayen'), (748, 'Swaziland'), (752, 'Sweden'), (756, 'Switzerland'), (760, 'Syrian Arab Republic'), (158, 'Taiwan, Province of China'), (762, 'Tajikistan'), (834, 'Tanzania, United Republic of'), (764, 'Thailand'), (626, 'Timor-Leste'), (768, 'Togo'), (772, 'Tokelau'), (776, 'Tonga'), (780, 'Trinidad and Tobago'), (788, 'Tunisia'), (792, 'Turkey'), (795, 'Turkmenistan'), (796, 'Turks and Caicos Islands'), (798, 'Tuvalu'), (800, 'Uganda'), (804, 'Ukraine'), (784, 'United Arab Emirates'), (826, 'United Kingdom'), (840, 'United States'), (581, 'United States Minor Outlying Islands'), (858, 'Uruguay'), (860, 'Uzbekistan'), (548, 'Vanuatu'), (862, 'Venezuela, Bolivarian Republic of'), (704, 'Viet Nam'), (92, 'Virgin Islands, British'), (850, 'Virgin Islands, U.S.'), (876, 'Wallis and Futuna'), (732, 'Western Sahara'), (887, 'Yemen'), (894, 'Zambia'), (716, 'Zimbabwe')]), blank=True, default=list, null=True, size=None)),
                ('ruling_party', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'political entity',
                'verbose_name_plural': 'political entities',
            },
            bases=('facts.organization',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='position',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.Person'),
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='organizationshareholder',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='organization',
            name='headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Place'),
        ),
    ]
