# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markymark.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', markymark.fields.MarkdownField(blank=True)),
                ('status_indicator', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Announced/Under Negotiation'), (2, 'Preparatory Works'), (3, 'Started'), (4, 'Under Construction'), (5, 'Completed')], null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Document')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectDocuments',
        ),
    ]
