# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('locations', '0002_geocollection'),
        ('facts', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='initiatives',
            field=models.ManyToManyField(blank=True, to='infrastructure.Initiative'),
        ),
        migrations.AddField(
            model_name='organization',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='organizations_led', to='facts.Person'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facts.Organization', verbose_name='parent organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='related_events',
            field=models.ManyToManyField(blank=True, to='facts.Event'),
        ),
        migrations.AddField(
            model_name='ngotype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facts.NGOType'),
        ),
        migrations.AddField(
            model_name='ngorelation',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='ngomemberrelation',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='multilateraltype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facts.MultilateralType'),
        ),
        migrations.AddField(
            model_name='multilateralrelation',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='multilateralmemberrelation',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='militaryrelation',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='governmentrelation',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='financingtype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facts.FinancingType'),
        ),
        migrations.AddField(
            model_name='financingrelation',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facts.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='documents',
            field=models.ManyToManyField(blank=True, to='sources.Document'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.EventType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.ManyToManyField(blank=True, to='locations.Place'),
        ),
        migrations.AddField(
            model_name='companytype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facts.CompanyType'),
        ),
        migrations.AddField(
            model_name='companyrelation',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Organization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Political', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='political',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.PoliticalType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='political',
            name='related_organizations',
            field=models.ManyToManyField(related_name='related_politicalentities', through='facts.PoliticalRelation', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='personshareholder',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.FinancingOrganization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='organizationshareholder',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.FinancingOrganization', verbose_name='to'),
        ),
        migrations.AddField(
            model_name='ngorelation',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.NGO'),
        ),
        migrations.AddField(
            model_name='ngomemberrelation',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.NGO', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='geographic_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Region'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='members',
            field=models.ManyToManyField(related_name='ngo_memberships', through='facts.NGOMemberRelation', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.NGOType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='related_organizations',
            field=models.ManyToManyField(related_name='related_ngos', through='facts.NGORelation', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='multilateralrelation',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Multilateral', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='multilateralmemberrelation',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Multilateral', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='multilateral',
            name='members',
            field=models.ManyToManyField(related_name='multilateral_memberships', through='facts.MultilateralMemberRelation', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='multilateral',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.MultilateralType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='multilateral',
            name='related_organizations',
            field=models.ManyToManyField(related_name='related_multilaterals', through='facts.MultilateralRelation', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='militaryrelation',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Military', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='military',
            name='related_organizations',
            field=models.ManyToManyField(related_name='related_militaries', through='facts.MilitaryRelation', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='governmentrelation',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Government', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='government',
            name='related_organizations',
            field=models.ManyToManyField(related_name='related_governments', through='facts.GovernmentRelation', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='financingrelation',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.FinancingOrganization', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='financingorganization',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.FinancingType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='financingorganization',
            name='related_organizations',
            field=models.ManyToManyField(related_name='related_financers', through='facts.FinancingRelation', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='financingorganization',
            name='shareholder_organizations',
            field=models.ManyToManyField(related_name='holds_shares_of', through='facts.OrganizationShareholder', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='financingorganization',
            name='shareholder_people',
            field=models.ManyToManyField(related_name='holds_shares_of', through='facts.PersonShareholder', to='facts.Person'),
        ),
        migrations.AddField(
            model_name='companyrelation',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.Company', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='company',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.CompanyType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='company',
            name='related_organizations',
            field=models.ManyToManyField(related_name='related_companies', through='facts.CompanyRelation', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='company',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.CompanyStructure'),
        ),
    ]
