# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='geographic_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Region'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='staff_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Staff/Personnel count'),
        ),
    ]
