# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_auto_20160314_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, to='facts.ProjectDocument'),
        ),
    ]
