# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_auto_20160427_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name', 'created_at'], 'verbose_name_plural': 'all organizations'},
        ),
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
