# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_auto_20160314_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingorganization',
            name='sp_credit_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(201, 'AAA'), (202, 'AA+'), (203, 'AA'), (204, 'AA−'), (205, 'A+'), (206, 'A'), (207, 'A−'), (208, 'BBB+'), (209, 'BBB'), (210, 'BBB−'), (211, 'BB+'), (212, 'BB'), (213, 'BB−'), (214, 'B+'), (215, 'B'), (216, 'B−'), (217, 'CCC+'), (218, 'CCC'), (219, 'CCC−'), (220, 'CC'), (221, 'C'), (222, 'RD'), (223, 'SD'), (224, 'D')], null=True, verbose_name='Standard & Poors Credit Rating'),
        ),
    ]
