# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_auto_20160511_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='dissolution_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='dissolution_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='dissolution_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founding_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founding_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founding_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
