# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_auto_20160202_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='party',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
