# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:15
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Organization = apps.get_model("facts", "Organization")
    db_alias = schema_editor.connection.alias
    for org in Organization._base_manager.using(db_alias).filter(dissolution_date__isnull=False):
        org.dissolution_year = org.dissolution_date.year
        org.dissolution_month = org.dissolution_date.month
        org.dissolution_day = org.dissolution_date.day
        org.save()
    for org in Organization._base_manager.using(db_alias).filter(founding_date__isnull=False):
        org.founding_year = org.founding_date.year
        org.founding_month = org.founding_date.month
        org.founding_day = org.founding_date.day
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_auto_20160531_1014'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
