# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:09
from __future__ import unicode_literals

from django.db import migrations, models
from utilities.migrations import make_slug_forward, make_uuid_forward
import uuid


def create_slugs(apps, schema_editor):
    model_slugs = (
        ('organization', 'name'),
        ('companytype', 'name'),
        ('eventtype', 'name'),
        ('financingtype', 'name'),
        ('multilateraltype', 'name'),
        ('ngotype', 'name'),
        ('politicaltype', 'name'),
        ('companystructure', 'name'),
        ('event', 'name'),
    )
    for model_label, slug_src in model_slugs:
        func = make_slug_forward('facts', model_label, slug_src)
        func(apps, schema_editor)


def set_uuids(apps, schema_editor):
    func = make_uuid_forward('facts', 'person', 'identifier')
    func(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0005_auto_20160329_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystructure',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companytype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingtype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multilateraltype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngotype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='politicaltype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.RunPython(create_slugs, migrations.RunPython.noop),
        migrations.RunPython(set_uuids, migrations.RunPython.noop),
    ]
