# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0005_auto_20160531_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='dissolution_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='founding_date',
        ),
    ]
