# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('facts', '0007_auto_20160408_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(blank=True, to='locations.Country'),
        ),
        migrations.AlterField(
            model_name='governmentdetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Country'),
        ),
        migrations.AlterField(
            model_name='militarydetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Country'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='citizenships',
        ),
        migrations.AddField(
            model_name='person',
            name='citizenships',
            field=models.ManyToManyField(blank=True, to='locations.Country'),
        ),
        migrations.RemoveField(
            model_name='politicaldetails',
            name='countries',
        ),
        migrations.AddField(
            model_name='politicaldetails',
            name='countries',
            field=models.ManyToManyField(blank=True, to='locations.Country'),
        ),
    ]
