# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0008_auto_20160408_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='values',
            new_name='dictionary',
        ),
    ]
