# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:51
from __future__ import unicode_literals

import datautils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0009_auto_20160418_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.CharField(blank=True, max_length=1000, validators=[datautils.validators.URLLikeValidator]),
        ),
    ]
