# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:56
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Person = apps.get_model("facts", "Person")
    db_alias = schema_editor.connection.alias
    for org in Person.objects.using(db_alias).filter(birth_date__isnull=False):
        org.birth_year = org.birth_date.year
        org.birth_month = org.birth_date.month
        org.birth_day = org.birth_date.day
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0010_auto_20160531_1056'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
