# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:58
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Position = apps.get_model("facts", "Position")
    db_alias = schema_editor.connection.alias
    for org in Position.objects.using(db_alias).filter(start_date__isnull=False):
        org.start_year = org.start_date.year
        org.start_month = org.start_date.month
        org.start_day = org.start_date.day
        org.save()
    for org in Position.objects.using(db_alias).filter(end_date__isnull=False):
        org.end_year = org.end_date.year
        org.end_month = org.end_date.month
        org.end_day = org.end_date.day
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0011_auto_20160531_1056'),
    ]

    operations = [
    ]
