# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0012_auto_20160531_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='position',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='position',
            name='start_date',
        ),
    ]
