# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0013_auto_20160531_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primary (raw materials)'), (2, 'Secondary (manufacturing)'), (3, 'Tertiary (sales and services)')], null=True), blank=True, default=list, size=None),
        ),
    ]
