# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0015_auto_20160613_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='sector',
        ),
    ]
