# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0017_auto_20160624_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family_name', 'given_name', 'additional_name'], 'verbose_name_plural': 'people'},
        ),
    ]
