# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20160706_1158'),
        ('facts', '0018_auto_20160629_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financingorganizationdetails',
            name='scope_of_operations',
        ),
        migrations.AddField(
            model_name='financingorganizationdetails',
            name='scope_of_operations',
            field=models.ManyToManyField(blank=True, to='locations.Place'),
        ),
    ]
