# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20160706_1158'),
        ('facts', '0019_auto_20160725_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngodetails',
            name='geographic_scope',
        ),
        migrations.AddField(
            model_name='ngodetails',
            name='geographic_scope',
            field=models.ManyToManyField(blank=True, help_text='Geographic scope as defined by a selection of Place records.', to='locations.Place'),
        ),
    ]
