# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import markymark.fields
from markymark.utils import render_markdown


def render_event_descriptions(apps, schema_editor):
    Event = apps.get_model("facts", "Event")
    db_alias = schema_editor.connection.alias
    for obj in Event.objects.using(db_alias).exclude(description=''):
        obj.description_rendered = render_markdown(obj.description)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('facts', '0021_auto_20160725_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.RunPython(render_event_descriptions, migrations.RunPython.noop),
        migrations.AddField(
            model_name='person',
            name='description',
            field=markymark.fields.MarkdownField(blank=True, verbose_name='Bio/Description'),
        ),
        migrations.AddField(
            model_name='person',
            name='description_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Preferably a portrait/"head shot".', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
    ]
