# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import markymark.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0022_auto_20160725_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=markymark.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
