# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models
from markymark.utils import render_markdown
import mptt


def render_organization_missions(apps, schema_editor):
    Organization = apps.get_model("facts", "Organization")
    mptt.register(Organization)
    db_alias = schema_editor.connection.alias
    for obj in Organization.objects.using(db_alias).exclude(mission=''):
        obj.mission_rendered = render_markdown(obj.mission)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0023_auto_20160725_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mission_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.RunPython(render_organization_missions, migrations.RunPython.noop),
    ]
