# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0025_auto_20160822_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingorganizationdetails',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='financingorganization_memberships', to='facts.Organization'),
        ),
    ]
