# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 18:36
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuids(apps, schema_editor):
    Organization = apps.get_model("facts", "Organization")
    db_alias = schema_editor.connection.alias

    # _base_manager is needed as Organization.objects is MPTTModelManager
    for obj in Organization._base_manager.using(db_alias).all():
        obj.identifier = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0027_add_organization_identifier_field'),
    ]

    operations = [
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
    ]
