# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0029_remove_organization_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationshareholder',
            options={'ordering': ['investment', '-value']},
        ),
        migrations.AlterModelOptions(
            name='personshareholder',
            options={'ordering': ['investment', '-value']},
        ),
    ]
