# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0031_auto_20161031_1316'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companytype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='eventtype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='financingtype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='multilateraltype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ngotype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='politicaltype',
            managers=[
            ],
        ),
    ]
