# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0032_auto_20170602_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['id']},
        ),
    ]
