# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0033_auto_20180413_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=130),
        ),
    ]
