# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import markymark.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('body', markymark.fields.MarkdownField()),
                ('body_rendered', models.TextField(blank=True)),
            ],
        ),
    ]
