# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 20:40
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_auto_20160209_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=mptt.fields.TreeManyToManyField(to='knowledgebase.Category'),
        ),
    ]
