# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 20:41
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, to='knowledgebase.Category'),
        ),
    ]
