# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 15:36
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_auto_20160209_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, to='knowledgebase.Category'),
        ),
    ]
