# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 16:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import markymark.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('locations', '0001_initial'),
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('notes', markymark.fields.MarkdownField(blank=True)),
                ('founding_date', models.DateField(blank=True, null=True, verbose_name='Founding/Signing Date')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('affiliated_events', models.ManyToManyField(blank=True, to='facts.Event')),
                ('affiliated_organizations', models.ManyToManyField(blank=True, to='facts.Organization')),
                ('affiliated_people', models.ManyToManyField(blank=True, to='facts.Person')),
                ('geographic_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Region')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, verbose_name='Project name/title')),
                ('total_cost_description', models.CharField(blank=True, max_length=100, verbose_name='Total Project Cost')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('commencement_date', models.DateField(blank=True, null=True, verbose_name='Date of commencement of works')),
                ('planned_completion_date', models.DateField(blank=True, null=True, verbose_name='Planned completion date')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Announced/Under Negotiation'), (2, 'Preparatory Works'), (3, 'Started'), (4, 'Under Construction'), (5, 'Completed')], default=1, null=True)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, help_text='Enter URLs separated by commas.', null=True, size=None, verbose_name='Sources URLs')),
                ('notes', markymark.fields.MarkdownField(blank=True)),
                ('consultants', models.ManyToManyField(blank=True, related_name='projects_consulted', to='facts.Organization', verbose_name='Consultants')),
                ('contacts', models.ManyToManyField(blank=True, related_name='projects_contacts', to='facts.Person', verbose_name='Points of contact')),
                ('contractors', models.ManyToManyField(blank=True, related_name='projects_contracted', to='facts.Organization', verbose_name='Contractors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.PositiveSmallIntegerField(blank=True, choices=[('Public Materials', ((1, 'Press Releases'), (2, 'Presentations & Brochures'), (3, 'National Development Plans'))), ('Agreements/Contracts', ((4, 'MoU'), (5, 'Financing Agreements'), (6, 'Procurement Contracts'), (7, 'Other Agreements'))), ('Operational Documents', ((8, 'Concept Notes'), (9, 'Review and Approval Documents'), (10, 'Procurement Documents'), (11, 'Appraisal Documents'), (12, 'Administration Manuals'), (13, 'Aide-Memoires'), (14, 'Financial Audits'))), ('Impact Assessment and Monitoring Reports', ((15, 'Environmental and Social Assessment'), (16, 'Resettlement Frameworks'), (17, 'Safeguards Monitoring Reports'), (18, 'Consultation Minutes'))), ('Implementation Progress Reports', ((19, 'Progress Reports'), (20, 'Completion Reports'))), ('Miscellaneous Reports', ((21, 'Miscellaneous Reports'),))], null=True, verbose_name='type')),
                ('notes', markymark.fields.MarkdownField(blank=True)),
                ('status_indicator', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Announced/Under Negotiation'), (2, 'Preparatory Works'), (3, 'Started'), (4, 'Under Construction'), (5, 'Completed')], null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.Document')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, help_text='Values in whole units (dollars, etc.)', null=True)),
                ('currency', models.CharField(blank=True, choices=[('IDR', 'Rupiah'), ('BWP', 'Pula'), ('AOA', 'Kwanza'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwe Dollar'), ('BBD', 'Barbados Dollar'), ('MAD', 'Moroccan Dirham'), ('BMD', 'Bermudian Dollar'), ('GHS', 'Ghana Cedi'), ('NPR', 'Nepalese Rupee'), ('CAD', 'Canadian Dollar'), ('MRO', 'Ouguiya'), ('BZD', 'Belize Dollar'), ('TND', 'Tunisian Dinar'), ('MKD', 'Denar'), ('MNT', 'Tugrik'), ('PEN', 'Sol'), ('AWG', 'Aruban Florin'), ('GTQ', 'Quetzal'), ('MDL', 'Moldovan Leu'), ('LKR', 'Sri Lanka Rupee'), ('WST', 'Tala'), ('NOK', 'Norwegian Krone'), ('SZL', 'Lilangeni'), ('MUR', 'Mauritius Rupee'), ('HKD', 'Hong Kong Dollar'), ('MXN', 'Mexican Peso'), ('KPW', 'North Korean Won'), ('SYP', 'Syrian Pound'), ('XAF', 'CFA Franc BEAC'), ('LAK', 'Kip'), ('KRW', 'Won'), ('GNF', 'Guinea Franc'), ('TWD', 'New Taiwan Dollar'), ('DJF', 'Djibouti Franc'), ('TZS', 'Tanzanian Shilling'), ('KGS', 'Som'), ('BDT', 'Taka'), ('GBP', 'Pound Sterling'), ('KYD', 'Cayman Islands Dollar'), ('RWF', 'Rwanda Franc'), ('PLN', 'Zloty'), ('BND', 'Brunei Dollar'), ('NGN', 'Naira'), ('STD', 'Dobra'), ('MVR', 'Rufiyaa'), ('ERN', 'Nakfa'), ('MZN', 'Mozambique Metical'), ('MWK', 'Malawi Kwacha'), ('CUC', 'Peso Convertible'), ('VUV', 'Vatu'), ('NZD', 'New Zealand Dollar'), ('GMD', 'Dalasi'), ('CHE', 'WIR Euro'), ('HUF', 'Forint'), ('ETB', 'Ethiopian Birr'), ('JMD', 'Jamaican Dollar'), ('AUD', 'Australian Dollar'), ('CNY', 'Yuan Renminbi'), ('LRD', 'Liberian Dollar'), ('SRD', 'Surinam Dollar'), ('DKK', 'Danish Krone'), ('CVE', 'Cabo Verde Escudo'), ('MMK', 'Kyat'), ('MGA', 'Malagasy Ariary'), ('KWD', 'Kuwaiti Dinar'), ('XPF', 'CFP Franc'), ('SAR', 'Saudi Riyal'), ('EGP', 'Egyptian Pound'), ('SCR', 'Seychelles Rupee'), ('BTN', 'Ngultrum'), ('VND', 'Dong'), ('AFN', 'Afghani'), ('BGN', 'Bulgarian Lev'), ('CHW', 'WIR Franc'), ('BHD', 'Bahraini Dinar'), ('UYI', 'Uruguay Peso en Unidades Indexadas (URUIURUI)'), ('CZK', 'Czech Koruna'), ('HNL', 'Lempira'), ('HTG', 'Gourde'), ('TOP', 'Pa’anga'), ('KMF', 'Comoro Franc'), ('UZS', 'Uzbekistan Sum'), ('UYU', 'Peso Uruguayo'), ('INR', 'Indian Rupee'), ('RSD', 'Serbian Dinar'), ('ANG', 'Netherlands Antillean Guilder'), ('MXV', 'Mexican Unidad de Inversion (UDI)'), ('SDG', 'Sudanese Pound'), ('EUR', 'Euro'), ('JPY', 'Yen'), ('XCD', 'East Caribbean Dollar'), ('TRY', 'Turkish Lira'), ('SGD', 'Singapore Dollar'), ('SEK', 'Swedish Krona'), ('OMR', 'Rial Omani'), ('SBD', 'Solomon Islands Dollar'), ('CLP', 'Chilean Peso'), ('GEL', 'Lari'), ('UAH', 'Hryvnia'), ('CDF', 'Congolese Franc'), ('RON', 'Romanian Leu'), ('SLL', 'Leone'), ('QAR', 'Qatari Rial'), ('MYR', 'Malaysian Ringgit'), ('CHF', 'Swiss Franc'), ('NIO', 'Cordoba Oro'), ('USN', 'US Dollar (Next day)'), ('SSP', 'South Sudanese Pound'), ('BAM', 'Convertible Mark'), ('FJD', 'Fiji Dollar'), ('PHP', 'Philippine Peso'), ('PAB', 'Balboa'), ('YER', 'Yemeni Rial'), ('KHR', 'Riel'), ('FKP', 'Falkland Islands Pound'), ('MOP', 'Pataca'), ('KES', 'Kenyan Shilling'), ('CRC', 'Costa Rican Colon'), ('COP', 'Colombian Peso'), ('TTD', 'Trinidad and Tobago Dollar'), ('LBP', 'Lebanese Pound'), ('PYG', 'Guarani'), ('IRR', 'Iranian Rial'), ('THB', 'Baht'), ('IQD', 'Iraqi Dinar'), ('ALL', 'Lek'), ('DOP', 'Dominican Peso'), ('AMD', 'Armenian Dram'), ('CUP', 'Cuban Peso'), ('BIF', 'Burundi Franc'), ('AZN', 'Azerbaijanian Manat'), ('HRK', 'Kuna'), ('SVC', 'El Salvador Colon'), ('KZT', 'Tenge'), ('BOV', 'Mvdol'), ('ARS', 'Argentine Peso'), ('BSD', 'Bahamian Dollar'), ('PKR', 'Pakistan Rupee'), ('XOF', 'CFA Franc BCEAO'), ('LYD', 'Libyan Dinar'), ('BOB', 'Boliviano'), ('BRL', 'Brazilian Real'), ('SOS', 'Somali Shilling'), ('PGK', 'Kina'), ('ZAR', 'Rand'), ('DZD', 'Algerian Dinar'), ('JOD', 'Jordanian Dinar'), ('GYD', 'Guyana Dollar'), ('VEF', 'Bolívar'), ('TJS', 'Somoni'), ('CLF', 'Unidad de Fomento'), ('SHP', 'Saint Helena Pound'), ('LSL', 'Loti'), ('NAD', 'Namibia Dollar'), ('GIP', 'Gibraltar Pound'), ('USD', 'US Dollar'), ('RUB', 'Russian Ruble'), ('BYR', 'Belarusian Ruble'), ('ISK', 'Iceland Krona'), ('AED', 'UAE Dirham'), ('UGX', 'Uganda Shilling'), ('COU', 'Unidad de Valor Real'), ('TMT', 'Turkmenistan New Manat'), ('ILS', 'New Israeli Sheqel')], default='USD', max_length=3, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.Organization')),
            ],
            options={
                'verbose_name_plural': 'project funders',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='countries',
            field=models.ManyToManyField(blank=True, to='locations.Country'),
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, to='infrastructure.ProjectDocument'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding',
            field=models.ManyToManyField(blank=True, related_name='projects_funded', through='infrastructure.ProjectFunding', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='implementers',
            field=models.ManyToManyField(blank=True, related_name='projects_implemented', to='facts.Organization', verbose_name='Client or implementing agency/ies'),
        ),
        migrations.AddField(
            model_name='project',
            name='infrastructure_type',
            field=models.ForeignKey(blank=True, help_text='Select or create named infrastructure types.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.InfrastructureType'),
        ),
        migrations.AddField(
            model_name='project',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.Initiative'),
        ),
        migrations.AddField(
            model_name='project',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_operated', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Select or create geographic region names.', to='locations.Region'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='initiative_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.InitiativeType'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='infrastructure.Initiative', verbose_name='parent initiative'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='principal_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_initiatives', to='facts.Person'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='member_countries',
            field=models.ManyToManyField(blank=True, to='locations.Country'),
        ),
    ]
