# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructuretype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='initiativetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projectfunding',
            name='currency',
            field=models.CharField(blank=True, choices=[('CDF', 'Congolese Franc'), ('SSP', 'South Sudanese Pound'), ('GIP', 'Gibraltar Pound'), ('MXN', 'Mexican Peso'), ('UYU', 'Peso Uruguayo'), ('ANG', 'Netherlands Antillean Guilder'), ('DOP', 'Dominican Peso'), ('IRR', 'Iranian Rial'), ('CUC', 'Peso Convertible'), ('SCR', 'Seychelles Rupee'), ('SGD', 'Singapore Dollar'), ('KRW', 'Won'), ('SBD', 'Solomon Islands Dollar'), ('RWF', 'Rwanda Franc'), ('SOS', 'Somali Shilling'), ('CLP', 'Chilean Peso'), ('BDT', 'Taka'), ('MAD', 'Moroccan Dirham'), ('PYG', 'Guarani'), ('BIF', 'Burundi Franc'), ('LBP', 'Lebanese Pound'), ('AED', 'UAE Dirham'), ('EGP', 'Egyptian Pound'), ('TMT', 'Turkmenistan New Manat'), ('KWD', 'Kuwaiti Dinar'), ('ISK', 'Iceland Krona'), ('SEK', 'Swedish Krona'), ('PAB', 'Balboa'), ('VND', 'Dong'), ('KMF', 'Comoro Franc'), ('BSD', 'Bahamian Dollar'), ('MWK', 'Malawi Kwacha'), ('WST', 'Tala'), ('BOV', 'Mvdol'), ('LYD', 'Libyan Dinar'), ('MUR', 'Mauritius Rupee'), ('STD', 'Dobra'), ('IQD', 'Iraqi Dinar'), ('COU', 'Unidad de Valor Real'), ('JOD', 'Jordanian Dinar'), ('KHR', 'Riel'), ('IDR', 'Rupiah'), ('KPW', 'North Korean Won'), ('UGX', 'Uganda Shilling'), ('XAF', 'CFA Franc BEAC'), ('LAK', 'Kip'), ('ERN', 'Nakfa'), ('GYD', 'Guyana Dollar'), ('OMR', 'Rial Omani'), ('USD', 'US Dollar'), ('PGK', 'Kina'), ('EUR', 'Euro'), ('USN', 'US Dollar (Next day)'), ('RUB', 'Russian Ruble'), ('MMK', 'Kyat'), ('BRL', 'Brazilian Real'), ('HKD', 'Hong Kong Dollar'), ('BOB', 'Boliviano'), ('SDG', 'Sudanese Pound'), ('JMD', 'Jamaican Dollar'), ('HRK', 'Kuna'), ('ILS', 'New Israeli Sheqel'), ('NZD', 'New Zealand Dollar'), ('TJS', 'Somoni'), ('SVC', 'El Salvador Colon'), ('XCD', 'East Caribbean Dollar'), ('XOF', 'CFA Franc BCEAO'), ('JPY', 'Yen'), ('PEN', 'Sol'), ('MOP', 'Pataca'), ('AWG', 'Aruban Florin'), ('ZWL', 'Zimbabwe Dollar'), ('SYP', 'Syrian Pound'), ('BAM', 'Convertible Mark'), ('FKP', 'Falkland Islands Pound'), ('ZAR', 'Rand'), ('MZN', 'Mozambique Metical'), ('NIO', 'Cordoba Oro'), ('AUD', 'Australian Dollar'), ('MRO', 'Ouguiya'), ('TZS', 'Tanzanian Shilling'), ('UZS', 'Uzbekistan Sum'), ('CHW', 'WIR Franc'), ('CNY', 'Yuan Renminbi'), ('UAH', 'Hryvnia'), ('SHP', 'Saint Helena Pound'), ('CVE', 'Cabo Verde Escudo'), ('LSL', 'Loti'), ('GMD', 'Dalasi'), ('HNL', 'Lempira'), ('AFN', 'Afghani'), ('ALL', 'Lek'), ('ARS', 'Argentine Peso'), ('BND', 'Brunei Dollar'), ('TWD', 'New Taiwan Dollar'), ('MVR', 'Rufiyaa'), ('AMD', 'Armenian Dram'), ('NOK', 'Norwegian Krone'), ('TND', 'Tunisian Dinar'), ('FJD', 'Fiji Dollar'), ('CAD', 'Canadian Dollar'), ('PLN', 'Zloty'), ('BGN', 'Bulgarian Lev'), ('BBD', 'Barbados Dollar'), ('GTQ', 'Quetzal'), ('RSD', 'Serbian Dinar'), ('XPF', 'CFP Franc'), ('MKD', 'Denar'), ('KZT', 'Tenge'), ('MDL', 'Moldovan Leu'), ('TTD', 'Trinidad and Tobago Dollar'), ('BZD', 'Belize Dollar'), ('HTG', 'Gourde'), ('CUP', 'Cuban Peso'), ('DZD', 'Algerian Dinar'), ('GBP', 'Pound Sterling'), ('AOA', 'Kwanza'), ('INR', 'Indian Rupee'), ('NAD', 'Namibia Dollar'), ('YER', 'Yemeni Rial'), ('BWP', 'Pula'), ('BMD', 'Bermudian Dollar'), ('THB', 'Baht'), ('PHP', 'Philippine Peso'), ('VEF', 'Bolívar'), ('MXV', 'Mexican Unidad de Inversion (UDI)'), ('MYR', 'Malaysian Ringgit'), ('NPR', 'Nepalese Rupee'), ('SAR', 'Saudi Riyal'), ('KYD', 'Cayman Islands Dollar'), ('CHF', 'Swiss Franc'), ('SRD', 'Surinam Dollar'), ('SZL', 'Lilangeni'), ('VUV', 'Vatu'), ('GNF', 'Guinea Franc'), ('KGS', 'Som'), ('RON', 'Romanian Leu'), ('COP', 'Colombian Peso'), ('CRC', 'Costa Rican Colon'), ('TOP', 'Pa’anga'), ('BTN', 'Ngultrum'), ('CHE', 'WIR Euro'), ('CLF', 'Unidad de Fomento'), ('UYI', 'Uruguay Peso en Unidades Indexadas (URUIURUI)'), ('NGN', 'Naira'), ('DJF', 'Djibouti Franc'), ('CZK', 'Czech Koruna'), ('MNT', 'Tugrik'), ('QAR', 'Qatari Rial'), ('HUF', 'Forint'), ('LKR', 'Sri Lanka Rupee'), ('TRY', 'Turkish Lira'), ('DKK', 'Danish Krone'), ('MGA', 'Malagasy Ariary'), ('SLL', 'Leone'), ('BYR', 'Belarusian Ruble'), ('LRD', 'Liberian Dollar'), ('ZMW', 'Zambian Kwacha'), ('AZN', 'Azerbaijanian Manat'), ('PKR', 'Pakistan Rupee'), ('KES', 'Kenyan Shilling'), ('BHD', 'Bahraini Dinar'), ('ETB', 'Ethiopian Birr'), ('GEL', 'Lari'), ('GHS', 'Ghana Cedi')], default='USD', max_length=3, null=True),
        ),
    ]
