# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 21:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import markymark.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_auto_20160317_1556'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_description', models.CharField(blank=True, max_length=100, verbose_name='Amount')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='funding_sources',
        ),
        migrations.AddField(
            model_name='project',
            name='commencement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of commencement of works'),
        ),
        migrations.AddField(
            model_name='project',
            name='consultants',
            field=models.ManyToManyField(blank=True, related_name='projects_consulted', to='facts.Organization', verbose_name='Consultants'),
        ),
        migrations.AddField(
            model_name='project',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='projects_contacts', to='facts.Person', verbose_name='Points of contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractors',
            field=models.ManyToManyField(blank=True, related_name='projects_contracted', to='facts.Organization', verbose_name='Contractors'),
        ),
        migrations.AddField(
            model_name='project',
            name='implementers',
            field=models.ManyToManyField(blank=True, related_name='projects_implemented', to='facts.Organization', verbose_name='Client or implementing agency/ies'),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=markymark.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_operated', to='facts.Organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned completion date'),
        ),
        migrations.AddField(
            model_name='project',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='Enter URLs separated by commas.', null=True, size=None, verbose_name='Sources URLs'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_cost_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Total Project Cost'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Public Materials', ((1, 'Press Releases'), (2, 'Presentations & Brochures'), (3, 'National Development Plans'))), ('Agreements/Contracts', ((4, 'MoU'), (5, 'Financing Agreements'), (6, 'Procurement Contracts'), (7, 'Other Agreements'))), ('Operational Documents', ((8, 'Concept Notes'), (9, 'Review and Approval Documents'), (10, 'Procurement Documents'), (11, 'Appraisal Documents'), (12, 'Administration Manuals'), (13, 'Aide-Memoires'), (14, 'Financial Audits'))), ('Impact Assessment and Monitoring Reports', ((15, 'Environmental and Social Assessment'), (16, 'Resettlement Frameworks'), (17, 'Safeguards Monitoring Reports'), (18, 'Consultation Minutes'))), ('Implementation Progress Reports', ((19, 'Progress Reports'), (20, 'Completion Reports'))), ('Miscellaneous Reports', ((21, 'Miscellaneous Reports'),))], null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Project name/title'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.Document'),
        ),
        migrations.AddField(
            model_name='projectfunding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Project'),
        ),
        migrations.AddField(
            model_name='projectfunding',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.FinancingOrganization'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding',
            field=models.ManyToManyField(blank=True, related_name='projects_funded', through='infrastructure.ProjectFunding', to='facts.FinancingOrganization'),
        ),
    ]
