# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:43
from __future__ import unicode_literals

from django.db import migrations, models


def one_to_many_initiatives(apps, schema_editor):
    Project = apps.get_model("infrastructure", "Project")
    db_alias = schema_editor.connection.alias
    for proj in Project.objects.using(db_alias).filter(initiative__isnull=False):
        proj.initiatives.add(proj.initiative)


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='initiatives',
            field=models.ManyToManyField(blank=True, to='infrastructure.Initiative'),
        ),
        migrations.RunPython(one_to_many_initiatives, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='project',
            name='initiative',
        ),
    ]
