# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20160325_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
