# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20160510_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
