# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def gen_uuids(apps, schema_editor):
    Project = apps.get_model("infrastructure", "Project")
    Initiative = apps.get_model("infrastructure", "Initiative")
    db_alias = schema_editor.connection.alias

    for obj in Project.objects.using(db_alias).all():
        obj.identifier = uuid.uuid4()
        obj.save()
    for obj in Initiative._base_manager.using(db_alias).all():
        obj.identifier = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_add_uuid_fields'),
    ]

    operations = [
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
    ]
