# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_projectdocument_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new',
            field=models.NullBooleanField(verbose_name='New Construction?'),
        ),
    ]
