# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_data'),
        ('infrastructure', '0005_project_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_data',
            field=models.ManyToManyField(blank=True, to='facts.Data'),
        ),
    ]
