# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 20:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_auto_20160328_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, help_text='Enter URLs separated by commas.', null=True, size=None, verbose_name='Sources URLs'),
        ),
    ]
