# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_auto_20160511_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='principal_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_initiatives', to='facts.Organization'),
        ),
    ]
