# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_auto_20160518_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='founding_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Founding/Signing Day'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='founding_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Founding/Signing Month'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='founding_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Founding/Signing Year'),
        ),
    ]
