# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_auto_20160329_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
