# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 21:16
from __future__ import unicode_literals

from django.db import migrations, models
from datautils.migrations import make_slug_forward, make_uuid_forward
import uuid


def create_slugs(apps, schema_editor):
    model_slugs = (
        ('infrastructuretype', 'name'),
        ('initiative', 'name'),
        ('initiativetype', 'name'),
        ('project', 'name')
    )
    for model_label, slug_src in model_slugs:
        func = make_slug_forward('infrastructure', model_label, slug_src)
        func(apps, schema_editor)


def set_uuids(apps, schema_editor):
    func = make_uuid_forward('infrastructure', 'projectdocument', 'identifier')
    func(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_auto_20160329_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructuretype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiativetype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', max_length=210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(create_slugs, migrations.RunPython.noop),
        migrations.RunPython(set_uuids, migrations.RunPython.noop),
    ]
