# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 21:16
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify
import uuid


def make_slug_forward(model_name, slug_source):
    def generate_slugs(apps, schema_editor):
        SluggableModel = apps.get_model('infrastructure', model_name)
        db_alias = schema_editor.connection.alias

        if hasattr(SluggableModel, 'objects'):
            for m in SluggableModel.objects.using(db_alias).all():
                if hasattr(m, 'slug'):
                    attr_val = getattr(m, slug_source)
                    if isinstance(attr_val, str):
                        m.slug = slugify(attr_val)
                        m.save(update_fields=['slug'])
    return generate_slugs


def create_slugs(apps, schema_editor):
    model_slugs = (
        ('infrastructuretype', 'name'),
        ('initiative', 'name'),
        ('initiativetype', 'name'),
        ('project', 'name')
    )
    for name, slug_src in model_slugs:
        func = make_slug_forward(name, slug_src)
        func(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_auto_20160329_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructuretype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiativetype',
            name='slug',
            field=models.SlugField(default='', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', max_length=210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(create_slugs, migrations.RunPython.noop)
    ]
