# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:03
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Initiative = apps.get_model("infrastructure", "Initiative")
    db_alias = schema_editor.connection.alias
    for org in Initiative._base_manager.using(db_alias).filter(founding_date__isnull=False):
        org.founding_year = org.founding_date.year
        org.founding_month = org.founding_date.month
        org.founding_day = org.founding_date.day
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_auto_20160531_1103'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
