# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import markymark.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_auto_20160531_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='founding_date',
        ),
        migrations.AddField(
            model_name='project',
            name='alternate_name',
            field=models.CharField(blank=True, help_text='Alternate name for project, suitable for display as a header', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=markymark.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
