# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20160407_1055'),
        ('infrastructure', '0010_auto_20160330_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiative',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='geometries',
            field=models.ManyToManyField(blank=True, to='locations.MultiGeometry'),
        ),
    ]
