# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_auto_20160610_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alternate_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=110),
        ),
    ]
