# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('infrastructure', '0011_auto_20160407_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='geodata',
        ),
        migrations.AddField(
            model_name='project',
            name='geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.GeometryStore'),
        ),
    ]
