# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_auto_20160408_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructuretype',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=110),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='initiativetype',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=110),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=210),
        ),
    ]
