# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 19:35
from __future__ import unicode_literals

from django.db import migrations
from infrastructure.models import ProjectStatus

status_cases = "\n".join(["WHEN status={0} THEN '{1}'".format(*s) for s in ProjectStatus.STATUSES])


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_auto_20160628_1814'),
    ]

    operations = [
        migrations.RunSQL([
            '''
            CREATE OR REPLACE VIEW infrastructure_regions_view AS
                SELECT l.project_id,
                    array_to_string(array_agg(quote_literal(r.name)), ', ', 'NULL') AS regions
                FROM infrastructure_project_regions AS l
                JOIN locations_region AS r
                ON l.region_id = r.id
                GROUP BY l.project_id;
            ''',
            '''
            CREATE OR REPLACE VIEW infrastructure_countries_view AS
                SELECT l.project_id,
                    array_to_string(array_agg(quote_literal(r.name)), ', ', 'NULL') AS countries
                FROM infrastructure_project_countries AS l
                JOIN locations_country AS r
                ON l.country_id = r.id
                GROUP BY l.project_id;
            ''',
            '''
            CREATE OR REPLACE VIEW infrastructure_initiatives_view AS
                SELECT l.project_id,
                    array_to_string(array_agg(quote_literal(r.name)), ', ', 'NULL') AS initiatives
                FROM infrastructure_project_initiatives AS l
                JOIN infrastructure_initiative AS r
                ON l.initiative_id = r.id
                GROUP BY l.project_id;
            ''',
            '''
            CREATE OR REPLACE VIEW infrastructure_contractors_view AS
                SELECT l.project_id,
                    array_to_string(array_agg(quote_literal(r.name)), ', ', 'NULL') AS contractors
                FROM infrastructure_project_contractors AS l
                JOIN facts_organization AS r
                ON l.organization_id = r.id
                GROUP BY l.project_id;
            ''',
            '''
            CREATE OR REPLACE VIEW infrastructure_consultants_view AS
                SELECT l.project_id,
                    array_to_string(array_agg(quote_literal(r.name)), ', ', 'NULL') AS consultants
                FROM infrastructure_project_consultants AS l
                JOIN facts_organization AS r
                ON l.organization_id = r.id
                GROUP BY l.project_id;
            ''',
            '''
            CREATE OR REPLACE VIEW infrastructure_implementers_view AS
                SELECT l.project_id,
                    array_to_string(array_agg(quote_literal(r.name)), ', ', 'NULL') AS implementing_agencies
                FROM infrastructure_project_implementers AS l
                JOIN facts_organization AS r
                ON l.organization_id = r.id
                GROUP BY l.project_id;
            ''',
            '''
            CREATE OR REPLACE VIEW infrastructure_operators_view AS
                SELECT l.project_id,
                    array_to_string(array_agg(quote_literal(r.name)), ', ', 'NULL') AS operators
                FROM infrastructure_project_operators AS l
                JOIN facts_organization AS r
                ON l.organization_id = r.id
                GROUP BY l.project_id;
            ''',
            '''
            CREATE OR REPLACE VIEW infrastructure_funding_view AS
                SELECT l.project_id,
                array_to_string(array_agg(quote_literal(org.name)), ' ', 'NULL') AS funding_sources,
                array_to_string(array_agg(l.amount), ' ', 'NULL') AS funding_amounts,
                array_to_string(array_agg(l.currency), ' ', 'NULL') AS funding_currencies
                FROM infrastructure_projectfunding AS l
                LEFT OUTER JOIN infrastructure_projectfunding_sources AS r ON l.id = r.projectfunding_id
                LEFT OUTER JOIN facts_organization AS org ON r.organization_id = org.id
                GROUP BY l.project_id;
            ''',
            '''
            CREATE OR REPLACE VIEW infrastructure_projects_export_view AS
                SELECT
                    identifier,
                    p.name,
                    t.name AS infrastructure_type,
                    related.countries,
                    related.regions,
                    related.contractors,
                    related.initiatives,
                    related.operators,
                    related.funding_sources,
                    related.funding_amounts,
                    related.funding_currencies,
                    CASE
                        {status_cases}
                        ELSE 'NULL'
                    END

                    status,
                    upper(new::text) as new,
                    upper(verified_path::text) AS verified,
                    total_cost,
                    total_cost_currency,
                    start_day,
                    start_month,
                    start_year,
                    commencement_day,
                    commencement_month,
                    commencement_year,
                    planned_completion_day,
                    planned_completion_month,
                    planned_completion_year
                FROM
                infrastructure_project AS p
                LEFT OUTER JOIN infrastructure_infrastructuretype AS t ON p.infrastructure_type_id = t.id
                LEFT OUTER JOIN
                    (
                        SELECT a.project_id,
                            countries,
                            regions,
                            contractors,
                            consultants,
                            operators,
                            implementing_agencies,
                            initiatives,
                            funding_sources,
                            funding_amounts,
                            funding_currencies
                        FROM
                            infrastructure_countries_view AS a
                            LEFT OUTER JOIN infrastructure_initiatives_view ON a.project_id = infrastructure_initiatives_view.project_id
                            LEFT OUTER JOIN infrastructure_regions_view ON a.project_id = infrastructure_regions_view.project_id
                            LEFT OUTER JOIN infrastructure_contractors_view ON a.project_id = infrastructure_contractors_view.project_id
                            LEFT OUTER JOIN infrastructure_consultants_view ON a.project_id = infrastructure_consultants_view.project_id
                            LEFT OUTER JOIN infrastructure_implementers_view ON a.project_id = infrastructure_implementers_view.project_id
                            LEFT OUTER JOIN infrastructure_operators_view ON a.project_id = infrastructure_operators_view.project_id
                            LEFT OUTER JOIN infrastructure_funding_view ON a.project_id = infrastructure_funding_view.project_id
                    )
                    AS related
                ON p.id = related.project_id;
            '''.format(status_cases=status_cases)
        ], [
            "DROP VIEW IF EXISTS infrastructure_projects_export_view;",
            "DROP VIEW IF EXISTS infrastructure_regions_view;",
            "DROP VIEW IF EXISTS infrastructure_countries_view;",
            "DROP VIEW IF EXISTS infrastructure_initiatives_view;",
            "DROP VIEW IF EXISTS infrastructure_contractors_view;",
            "DROP VIEW IF EXISTS infrastructure_consultants_view;",
            "DROP VIEW IF EXISTS infrastructure_implementers_view;",
            "DROP VIEW IF EXISTS infrastructure_operators_view;",
            "DROP VIEW IF EXISTS infrastructure_funding_view;",
        ])
    ]
