# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_auto_20160408_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='commencement_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='planned_completion_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='commencement_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day of commencement of works'),
        ),
        migrations.AddField(
            model_name='project',
            name='commencement_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Month of commencement of works'),
        ),
        migrations.AddField(
            model_name='project',
            name='commencement_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of commencement of works'),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_completion_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_completion_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_completion_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
