# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0014_project_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='related_initiatives',
            field=models.ManyToManyField(blank=True, related_name='_initiative_related_initiatives_+', to='infrastructure.Initiative'),
        ),
    ]
