# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20160706_1158'),
        ('infrastructure', '0016_initiative_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='geographic_scope',
        ),
        migrations.AddField(
            model_name='initiative',
            name='geographic_scope',
            field=models.ManyToManyField(blank=True, related_name='initiatives_in_scope', to='locations.Country'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='member_countries',
            field=models.ManyToManyField(blank=True, related_name='initiatives_joined', to='locations.Country'),
        ),
    ]
