# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0016_auto_20160422_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='appeared_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='First Apperance Day'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='appeared_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='First Apperance Month'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='appeared_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='First Apperance Year'),
        ),
    ]
