# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:51
from __future__ import unicode_literals

import datautils.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0017_auto_20160422_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000, validators=[datautils.validators.URLLikeValidator]), blank=True, default=list, help_text='Enter URLs separated by commas.', null=True, size=None, verbose_name='Sources URLs'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='source_url',
            field=models.CharField(blank=True, max_length=1000, validators=[datautils.validators.URLLikeValidator]),
        ),
    ]
