# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0017_auto_20160725_1248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='initiative',
            managers=[
                ('publishable_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Public Materials', ((1, 'Press Releases'), (2, 'Presentations & Brochures'), (3, 'National Development Plans'))), ('Agreements/Contracts', ((4, 'MoU'), (5, 'Financing Agreements'), (6, 'Procurement Contracts'), (7, 'Other Agreements'))), ('Operational Documents', ((8, 'Concept Notes'), (9, 'Review and Approval Documents'), (10, 'Procurement Documents'), (11, 'Appraisal Documents'), (12, 'Administration Manuals'), (13, 'Aide-Memoires'), (14, 'Financial Audits'))), ('Impact Assessment and Monitoring Reports', ((15, 'Environmental and Social Assessment'), (16, 'Resettlement Frameworks'), (17, 'Safeguards Monitoring Reports'), (18, 'Consultation Minutes'))), ('Implementation Progress Reports', ((19, 'Progress Reports'), (20, 'Completion Reports'))), ('Miscellaneous Reports', ((21, 'Miscellaneous Reports'),)), ('Unofficial Sources', ((22, 'Unofficial Sources'),))], null=True, verbose_name='type'),
        ),
    ]
