# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0010_auto_20160425_1251'),
        ('infrastructure', '0018_auto_20160425_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='operator',
        ),
        migrations.AddField(
            model_name='project',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='projects_operated', to='facts.Organization'),
        ),
    ]
