# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0018_auto_20160808_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructuretype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='initiativetype',
            options={'ordering': ['name']},
        ),
    ]
