# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0019_auto_20160915_1537'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='initiative',
            managers=[
            ],
        ),
    ]
