# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0010_auto_20160425_1251'),
        ('infrastructure', '0019_auto_20160426_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfunding',
            name='source',
        ),
        migrations.AddField(
            model_name='projectfunding',
            name='sources',
            field=models.ManyToManyField(blank=True, to='facts.Organization'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='funding',
        ),
        migrations.AddField(
            model_name='project',
            name='funding',
            field=models.ManyToManyField(blank=True, related_name='projects_funded', to='infrastructure.ProjectFunding'),
        ),
    ]
