# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0020_auto_20160426_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collection_stage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Identified'), (2, 'Collected')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='verified_path',
            field=models.NullBooleanField(),
        ),
    ]
