# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-12 20:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0020_auto_20170602_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='infrastructure.Initiative', verbose_name='parent initiative'),
        ),
    ]
