# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20180412_1618'),
        ('facts', '0033_auto_20180413_1525'),
        ('infrastructure', '0022_auto_20180418_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name_plural': 'fuel categories',
            },
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(allow_unicode=True, max_length=150)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Announced/Under Negotiation'), (2, 'Preparatory Works'), (3, 'Started'), (4, 'Under Construction'), (5, 'Completed'), (6, 'Cancelled')], null=True)),
                ('plant_year_online', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plant_month_online', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plant_day_online', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decommissioning_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decommissioning_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decommissioning_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plant_capacity', models.BigIntegerField(blank=True, help_text='MW', null=True)),
                ('plant_output', models.BigIntegerField(blank=True, null=True)),
                ('plant_output_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estimated_plant_output', models.BigIntegerField(blank=True, null=True)),
                ('plant_CO2_emissions', models.BigIntegerField(blank=True, null=True)),
                ('grid_connected', models.NullBooleanField(verbose_name='Grid connected?')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('countries', models.ManyToManyField(blank=True, to='locations.Country')),
                ('infrastructure_type', models.ForeignKey(blank=True, help_text='Select or create named insfrastructure types.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.InfrastructureType')),
                ('operators', models.ManyToManyField(blank=True, related_name='plants_operated', to='facts.Organization', verbose_name='Operators')),
                ('owners', models.ManyToManyField(blank=True, related_name='plants_contracted', to='facts.Organization', verbose_name='Owners')),
                ('regions', models.ManyToManyField(blank=True, help_text='Select or create geographic region names.', to='locations.Region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='construction_start_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='construction_start_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='construction_start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_project_output',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='implementing_agency',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, related_name='projects_manufactured', to='facts.Organization', verbose_name='Manufacturers'),
        ),
        migrations.AddField(
            model_name='project',
            name='nOx_reduction_system',
            field=models.NullBooleanField(verbose_name='NOx Reduction System?'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_CO2_emissions',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_capacity',
            field=models.BigIntegerField(blank=True, help_text='MW', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_output',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_output_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sOx_reudction_system',
            field=models.NullBooleanField(verbose_name='SOx Reduction System?'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_category',
            field=models.ForeignKey(blank=True, help_text='Select or create named fuel categories.', null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.FuelCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Fuel'),
        ),
        migrations.AddField(
            model_name='project',
            name='power_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.PowerPlant'),
        ),
    ]
