# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0023_auto_20180719_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerplant',
            name='estimated_plant_output_unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MWh'), (1, 'MW'), (2, 'Tonnes per annum')], null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='plant_CO2_emissions_unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MWh'), (1, 'MW'), (2, 'Tonnes per annum')], null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='plant_capacity_unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MWh'), (1, 'MW'), (2, 'Tonnes per annum')], null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='plant_output_unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MWh'), (1, 'MW'), (2, 'Tonnes per annum')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_project_output_unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MWh'), (1, 'MW'), (2, 'Tonnes per annum')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_CO2_emissions_unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MWh'), (1, 'MW'), (2, 'Tonnes per annum')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_capacity_unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MWh'), (1, 'MW'), (2, 'Tonnes per annum')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_output_unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MWh'), (1, 'MW'), (2, 'Tonnes per annum')], null=True),
        ),
    ]
