# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0023_curatedprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedproject',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
