# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20180412_1618'),
        ('infrastructure', '0023_auto_20180723_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerplant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='powerplant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='powerplant',
            name='geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_plants', to='locations.GeometryStore'),
        ),
    ]
