# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0024_auto_20180719_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerplant',
            name='estimated_plant_output',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='plant_CO2_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='plant_output',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_project_output',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_CO2_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_output',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
