# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-23 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0024_curatedprojects_published'),
        ('infrastructure', '0023_auto_20180723_1056'),
    ]

    operations = [
    ]
