# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import markymark.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0025_auto_20180801_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerplant',
            name='description',
            field=markymark.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='powerplant',
            name='description_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
