# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0026_auto_20180913_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerplant',
            name='plant_initiatives',
            field=models.ManyToManyField(blank=True, to='infrastructure.Initiative'),
        ),
    ]
