# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-02 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0026_auto_20180913_1555'),
    ]

    operations = [
        migrations.RunSQL(
        '''
        CREATE OR REPLACE VIEW infrastructure_power_plant_export_view
        AS SELECT pp.id,
            pp.created_at,
            pp.updated_at,
            pp.published,
            pp.name,
            pp.slug,
            pp.status,
            pp.plant_year_online,
            pp.plant_month_online,
            pp.plant_day_online,
            pp.decommissioning_year,
            pp.decommissioning_month,
            pp.decommissioning_day,
            pp.plant_capacity,
            pp.plant_capacity_unit,
            pp.plant_output,
            pp.plant_output_unit,
            pp.plant_output_year,
            pp.estimated_plant_output,
            pp.estimated_plant_output_unit,
            pp."plant_CO2_emissions",
            pp."plant_CO2_emissions_unit",
            pp.grid_connected,
            pp.infrastructure_type_id,
            pp.geo_id,
            pp.description,
            pp.description_rendered,
            array_to_string(array_agg(quote_literal(ipp.name::text)), ','::text, 'NULL'::text) as fuel_type,
            array_to_string(array_agg(quote_literal(ipfc.name::text)), ','::text, 'NULL'::text) as fuel_category
        FROM infrastructure_powerplant pp
            LEFT JOIN infrastructure_powerplant_fuels ippf ON ippf.powerplant_id = pp.id
            LEFT JOIN infrastructure_fuel ipp ON ippf.fuel_id = ipp.id
            LEFT JOIN infrastructure_fuelcategory ipfc ON ipp.fuel_category_id = ipfc.id
        GROUP by pp.id
        ''',
        "DROP VIEW public.infrastructure_power_plant_export_view"
        )
    ]
