# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-02 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0026_auto_20180913_1555'),
    ]

    operations = [
        migrations.RunSQL(
        '''
        CREATE OR REPLACE VIEW infrastructure_power_plant_export_view
        AS select pp.id, 
            pp.name,
            array_to_string(array_agg(quote_literal(lc.name::text)), ','::text, 'NULL'::text) as countries,
            array_to_string(array_agg(quote_literal(lr.name::text)), ','::text, 'NULL'::text) as regions,
            array_to_string(array_agg(quote_literal(lgeo.centroid::text)), ','::text, 'NULL'::text) as centroid,
            array_to_string(array_agg(quote_literal(fcown.name::text)), ','::text, 'NULL'::text) as owners,
            array_to_string(array_agg(quote_literal(fcop.name::text)), ','::text, 'NULL'::text) as operators,
            pp.slug,
            pp.status,
            pp.plant_year_online,
            pp.plant_month_online,
            pp.plant_day_online,
            pp.decommissioning_year,
            pp.decommissioning_month,
            pp.decommissioning_day,
            pp.plant_capacity,
            pp.plant_capacity_unit,
            pp.plant_output,
            pp.plant_output_unit,
            pp.plant_output_year,
            pp.estimated_plant_output,
            pp.estimated_plant_output_unit,
            pp."plant_CO2_emissions",
            pp."plant_CO2_emissions_unit",
            pp.grid_connected,
            pp.description,
            pp.created_at,
            pp.updated_at,
            pp.published
        from infrastructure_powerplant pp
        left join infrastructure_powerplant_countries ppct on ppct.powerplant_id = pp.id
            left join locations_country lc on lc.id= ppct.country_id
        left join infrastructure_powerplant_regions ppr on ppr.powerplant_id = pp.id
            left join locations_region lr on lr.id = ppr.region_id
        left join infrastructure_powerplant_owners ppown on ppown.powerplant_id = pp.id
            left join facts_organization fcown on fcown.id = ppown.organization_id
        left join infrastructure_powerplant_operators ppop on ppop.powerplant_id = pp.id
            left join facts_organization fcop on fcop.id = ppop.organization_id
        join locations_geometrystore lgeo on lgeo.id = pp.geo_id
        group by pp.id
        ''',
        "DROP VIEW public.infrastructure_power_plant_export_view"
        )
    ]
