# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0027_auto_20190105_1558'),
        ('infrastructure', '0027_powerplant_plant_initiatives'),
    ]

    operations = [
    ]
