# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 23:11
from __future__ import unicode_literals

from django.db import migrations
import markymark.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0028_merge_20190116_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerplant',
            name='notes',
            field=markymark.fields.MarkdownField(blank=True),
        ),
    ]
