# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 16:47
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

def forwards(apps, schema_editor):
    Project = apps.get_model('infrastructure', 'Project')
    prjs = Project.objects.filter(infrastructure_type__name="Powerplant")

    print("Moving construction dates to commencement dates for {} projects".format(prjs.count()))
    prjs.update(commencement_year=F('construction_start_year'), construction_start_year=None)
    prjs.update(commencement_month=F('construction_start_month'), construction_start_month=None)
    prjs.update(commencement_day=F('construction_start_day'), construction_start_day=None)

def backwards(apps, schema_editor):
    Project = apps.get_model('infrastructure', 'Project')
    prjs = Project.objects.filter(infrastructure_type__name="Powerplant")
    
    print("Moving commencement dates to construction dates for {} projects".format(len(prjs)))
    prjs.update(construction_start_year=F('commencement_year'), commencement_year=None)
    prjs.update(construction_start_month=F('commencement_month'), commencement_month=None)
    prjs.update(construction_start_day=F('commencement_day'), commencement_day=None)


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0030_auto_20190117_1812'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
