# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0030_auto_20190117_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerplant',
            name='owners',
        ),
    ]
