# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0031_auto_20190124_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='construction_start_day',
        ),
        migrations.RemoveField(
            model_name='project',
            name='construction_start_month',
        ),
        migrations.RemoveField(
            model_name='project',
            name='construction_start_year',
        ),
    ]
