# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-29 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0031_remove_powerplant_owners'),
        ('infrastructure', '0032_auto_20190124_1308'),
    ]

    operations = [
    ]
