# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 16:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import utilities.validators


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0033_merge_20190129_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerplant',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000, validators=[utilities.validators.URLLikeValidator]), blank=True, default=list, help_text='Enter URLs separated by commas.', null=True, size=None, verbose_name='Sources URLs'),
        ),
    ]
