# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0034_powerplant_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linear_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text='km', null=True),
        ),
    ]
