# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-08 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0035_project_linear_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnerStake',
            new_name='PlantOwnerStake',
        ),
    ]
