# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-08 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0033_auto_20180413_1525'),
        ('infrastructure', '0036_auto_20190208_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOwnerStake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_owned', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owners_stakes', to='facts.Organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner_stakes', to='infrastructure.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='plantownerstake',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_owners_stakes', to='facts.Organization'),
        ),
        migrations.AlterField(
            model_name='plantownerstake',
            name='power_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_owner_stakes', to='infrastructure.PowerPlant'),
        ),
    ]
