# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-11 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0036_projectsubstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='design_voltage',
            field=models.BigIntegerField(help_text='Design Voltage (kV)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='direct_current',
            field=models.NullBooleanField(help_text='Direct Current?'),
        ),
        migrations.AddField(
            model_name='project',
            name='electricity_flow',
            field=models.CharField(blank=True, choices=[('Bidirectional', 'bidirectional'), ('Unidirectional', 'unidirectional')], help_text='Electricity Flow (direction)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_transfer_capacity',
            field=models.BigIntegerField(help_text='Estimated Transfer Capacity (MW)', null=True),
        ),
    ]
