# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-11 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0037_auto_20190208_0946'),
        ('infrastructure', '0036_projectsubstation'),
    ]

    operations = [
    ]
