# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-11 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0038_merge_20190211_1038'),
        ('infrastructure', '0035_new_infrastructure_types'),
    ]

    operations = [
    ]
