# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-11 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0039_merge_20190211_1210'),
        ('infrastructure', '0039_transmission_fields'),
    ]

    operations = [
    ]
