# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0040_merge_20190211_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pipeline_diameter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pipeline Diameter'),
        ),
        migrations.AddField(
            model_name='project',
            name='pipeline_diameter_unit',
            field=models.CharField(blank=True, choices=[('inches', 'inches'), ('mm', 'mm')], help_text='Diameter unit', max_length=6, verbose_name='Diameter Unit'),
        ),
        migrations.AddField(
            model_name='project',
            name='pipeline_metered',
            field=models.NullBooleanField(verbose_name='Pipeline Metered?'),
        ),
        migrations.AddField(
            model_name='project',
            name='pipeline_throughput',
            field=models.IntegerField(blank=True, null=True, verbose_name='Throughput'),
        ),
        migrations.AddField(
            model_name='project',
            name='pipeline_throughput_timeframe',
            field=models.CharField(blank=True, choices=[('per-hour', 'per hour'), ('per-day', 'per day'), ('per-month', 'per month'), ('per-year', 'per year')], max_length=10, verbose_name='Throughput Timeframe'),
        ),
        migrations.AddField(
            model_name='project',
            name='pipeline_throughput_unit',
            field=models.CharField(blank=True, choices=[('barrels', 'Barrels'), ('tons', 'Tons'), ('million-cubic-feet', 'million cubic feet'), ('million-cubic-meters', 'million cubic meters'), ('billion-cubic-feet', 'billion cubic feet'), ('billion-cubic-meters', 'billion cubic meters')], max_length=20, verbose_name='Throughput Unit'),
        ),
        migrations.AddField(
            model_name='project',
            name='pipeline_throughput_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Throughput Year'),
        ),
    ]
