# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0042_project_project_capacity_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructuretype',
            name='show_on_map',
            field=models.BooleanField(default=True),
        ),
    ]
