# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 12:46
from __future__ import unicode_literals
from django.db import migrations, models
from infrastructure.export import refresh_views


def update_capacity_unit(apps, schema_editor):
    """
    Prior to this migration project_capacity_units were stored as integers. This migration
    transforms those integers into their new string representation.  At the time of this
    migration there were no project_capacity_units other than 1=mw
    """
    Project = apps.get_model('infrastructure', "Project")
    # The Alter table doesn't affect the original number except it is now a Char
    current_capacity_units = Project.objects.filter(project_capacity_unit='1')
    current_capacity_units.update(project_capacity_unit="mw")

    # Rebuild the VIEW that was dropped in the first operation.
    refresh_views()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('infrastructure', '0043_infrastructuretype_show_on_map'),
    ]

    # The VIEW must be dropped before the AlterField, to account for database constraints on
    # altering a table upon which the VIEW depends. It will be rebuilt in the last operation.
    operations = [
        migrations.RunSQL("DROP VIEW infrastructure_projects_export_view"),
        migrations.AlterField(
            model_name='project',
            name='project_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_capacity_unit',
            field=models.CharField(blank=True, default='', choices=[('mw', 'MW'), ('barrels', 'Barrels'), ('tons', 'Tons'), ('million-cubic-feet', 'million cubic feet'), ('million-cubic-meters', 'million cubic meters'), ('billion-cubic-feet', 'billion cubic feet'), ('billion-cubic-meters', 'billion cubic meters')], max_length=20),
        ),
        migrations.RunPython(update_capacity_unit),
    ]
