# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-14 19:28
from __future__ import unicode_literals

from django.db import migrations, models
from infrastructure.export import refresh_views


def clean_units(apps, schema_editor):
    Project = apps.get_model('infrastructure', "Project")
    # Pipeline
    objs_meters = Project.objects.filter(pipeline_throughput_unit__contains='cubic-meters')
    objs_feet = Project.objects.filter(pipeline_throughput_unit__contains='cubic-feet')
    objs_meters.update(pipeline_throughput_unit='cubic-meters')
    objs_feet.update(pipeline_throughput_unit='cubic-feet')
    # Project
    objs_meters = Project.objects.filter(project_capacity_unit__contains='cubic-meters')
    objs_feet = Project.objects.filter(project_capacity_unit__contains='cubic-feet')
    objs_meters.update(project_capacity_unit='cubic-meters')
    objs_feet.update(project_capacity_unit='cubic-feet')
    refresh_views()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('infrastructure', '0044_auto_20190301_0746'),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW infrastructure_projects_export_view"),
        migrations.AlterField(
            model_name='project',
            name='pipeline_throughput',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Throughput'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pipeline_throughput_unit',
            field=models.CharField(blank=True, choices=[('barrels', 'Barrels'), ('tons', 'Tons'), ('cubic-feet', 'cubic feet'), ('cubic-meters', 'cubic meters')], max_length=20, verbose_name='Throughput Unit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_capacity_unit',
            field=models.CharField(blank=True, choices=[('mw', 'MW'), ('barrels', 'Barrels'), ('tons', 'Tons'), ('cubic-feet', 'cubic feet'), ('cubic-meters', 'cubic meters')], default='', max_length=20),
        ),
        migrations.RunPython(clean_units),
    ]
