# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writings.EntryCollection')),
            ],
        ),
        migrations.AddField(
            model_name='orderedentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writings.Entry'),
        ),
        migrations.AddField(
            model_name='entrycollection',
            name='entries',
            field=models.ManyToManyField(related_name='ordered_collections', through='writings.OrderedEntry', to='writings.Entry'),
        ),
        migrations.AlterUniqueTogether(
            name='orderedentry',
            unique_together=set([('collection', 'order')]),
        ),
    ]
