# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0002_auto_20160721_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='related_entries',
            field=models.ManyToManyField(related_name='_entry_related_entries_+', to='writings.Entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='publication_date',
            field=models.DateTimeField(blank=True, help_text='<p>Publication date will be set to the current time automatically, when <em>published</em> is selected.\n        <p>You may set a date/time manually, but <strong>you must\n            select <em>published</em> for the post to appear!</strong>\n        ', null=True),
        ),
    ]
