# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0003_entry_related_entries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrycollection',
            options={'get_latest_by': 'publication_date', 'verbose_name': 'entry collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='orderedentry',
            options={'verbose_name': 'ordered entry', 'verbose_name_plural': 'ordered entries'},
        ),
    ]
