# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0006_auto_20161012_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedentry',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
