# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0007_auto_20161012_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedentry',
            options={'ordering': ['collection', 'order'], 'verbose_name': 'ordered entry', 'verbose_name_plural': 'ordered entries'},
        ),
    ]
