# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-30 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('writings', '0008_auto_20161012_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='sponsored_logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_article', to='filer.Image'),
        ),
    ]
