# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20160328_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL'),
        ),
    ]
