# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:51
from __future__ import unicode_literals

import utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20160329_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=1000, validators=[utilities.validators.URLLikeValidator], verbose_name='URL'),
        ),
    ]
