# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 15:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('collection', django.contrib.gis.db.models.fields.GeometryCollectionField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Geographic Collection',
            },
        ),
    ]
