# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 23:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('lon', models.FloatField(blank=True, help_text='Defines a geographic longitude')),
                ('lat', models.FloatField(blank=True, help_text='Defines a geographic latitude')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lon',
        ),
        migrations.AddField(
            model_name='place',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Marker'),
        ),
    ]
