# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linestringgeometry',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='multigeometry',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='pointgeometry',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='polygongeometry',
            old_name='geometry',
            new_name='geom',
        ),
    ]
