# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 14:42
from __future__ import unicode_literals

from django.db import migrations

DEFAULT_REGION_NAMES = (
    'Eastern Europe and the Balkans',
    'Gulf and Mediterranean',
    'Northeast Asia',
    'Russia, Central Asia, and the South Caucuses',
    'South Asia and India',
    'Southeast Asia',
    'Western Europe and Scandinavia'
)


def create_regions(apps, schema_editor):
    Region = apps.get_model("locations.Region")
    db_alias = schema_editor.connection.alias

    Region.objects.using(db_alias).bulk_create([
        Region(name=x) for x in DEFAULT_REGION_NAMES
    ])


def remove_regions(apps, schema_editor):
    Region = apps.get_model("locations.Region")
    db_alias = schema_editor.connection.alias

    for name in DEFAULT_REGION_NAMES:
        Region.objects.using(db_alias).filter(name=name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_geocollection'),
    ]

    operations = [
        migrations.RunPython(create_regions, remove_regions),
    ]
