# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20160408_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrystore',
            name='lines',
            field=models.ManyToManyField(related_name='geostores', to='locations.LineStringGeometry'),
        ),
        migrations.AlterField(
            model_name='geometrystore',
            name='points',
            field=models.ManyToManyField(related_name='geostores', to='locations.PointGeometry'),
        ),
        migrations.AlterField(
            model_name='geometrystore',
            name='polygons',
            field=models.ManyToManyField(related_name='geostores', to='locations.PolygonGeometry'),
        ),
    ]
