# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 14:42
from __future__ import unicode_literals

from django.db import migrations
from django.core import management


def load_regions_from_fixture(apps, schema_editor):
    management.call_command('loaddata', 'regions.json', app='locations', verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_geocollection'),
    ]

    operations = [
        migrations.RunPython(load_regions_from_fixture, migrations.RunPython.noop),
    ]
