# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20160304_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeographicLocation',
            new_name='GeoPoint',
        ),
        migrations.RenameModel(
            old_name='GeographicRegion',
            new_name='GeoRegion',
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.GeographicLocation', verbose_name='geographic location'),
        ),
    ]
