# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20160415_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrystore',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
