# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 14:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20160328_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='GeoCollection',
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.PointGeometry', verbose_name='geographic location'),
        ),
        migrations.AlterField(
            model_name='region',
            name='geography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.PolygonGeometry'),
        ),
        migrations.CreateModel(
            name='LineStringGeometry',
            fields=[
                ('geometryrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.GeometryRecord')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'verbose_name': 'line',
            },
            bases=('locations.geometryrecord',),
        ),
        migrations.CreateModel(
            name='MultiGeometry',
            fields=[
                ('geometryrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.GeometryRecord')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
            ],
            bases=('locations.geometryrecord',),
        ),
        migrations.CreateModel(
            name='PointGeometry',
            fields=[
                ('geometryrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.GeometryRecord')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'point',
            },
            bases=('locations.geometryrecord',),
        ),
        migrations.CreateModel(
            name='PolygonGeometry',
            fields=[
                ('geometryrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.GeometryRecord')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'polygon',
            },
            bases=('locations.geometryrecord',),
        ),
        migrations.DeleteModel(
            name='GeoPoint',
        ),
        migrations.DeleteModel(
            name='GeoRegion',
        ),
    ]
