# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20160407_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multigeometry',
            options={'verbose_name': 'geometry collection'},
        ),
    ]
