# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 20:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20160405_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrycollection',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
