# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20160502_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrystore',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='geostores', to='locations.LineStringGeometry'),
        ),
        migrations.AlterField(
            model_name='geometrystore',
            name='points',
            field=models.ManyToManyField(blank=True, related_name='geostores', to='locations.PointGeometry'),
        ),
        migrations.AlterField(
            model_name='geometrystore',
            name='polygons',
            field=models.ManyToManyField(blank=True, related_name='geostores', to='locations.PolygonGeometry'),
        ),
    ]
