# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20160503_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linestringgeometry',
            name='label',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='multigeometry',
            name='label',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='pointgeometry',
            name='label',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='polygongeometry',
            name='label',
            field=models.CharField(max_length=400),
        ),
    ]
