# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20160505_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrystore',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
