# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20160608_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=110),
            preserve_default=False,
        ),
    ]
