# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20160706_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('country__name', 'city')},
        ),
    ]
