# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-30 17:33
from __future__ import unicode_literals

from django.db import migrations


def move_projects_from_4_to_8_and_delete_4(apps, schema_editor):
    """
    Clean up Projects associated with one of the two
    "Russia, Central Asia, and the Sou(r)th Caucasus" Region
    instances by associating all of them with the
    misspelled variant (it's the one with more data
    attached to it, after all).
    """
    Region = apps.get_model('locations', 'Region')

    # strangely enough, we want to move all Projects over
    # to the instance that is currently *not* spelled right
    spelled_right = Region.objects.get(pk=4)
    spelled_wrong = Region.objects.get(pk=8)

    for project in spelled_right.project_set.all():
        project.regions.remove(spelled_right)
        project.regions.add(spelled_wrong)
        project.save()
    
    spelled_right.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20180412_1618'),
        ('infrastructure', '0033_merge_20190129_1135'),
    ]

    operations = [
        migrations.RunPython(move_projects_from_4_to_8_and_delete_4)
    ]
